### ISSUE TITLE
"accepts_nested_attributes_for"  ok when add  but  fails when update 

### ISSUE THREAD

**Issue by wanweidong** [composite-primary-keys/composite_primary_keys#141]
I use lasted code with "add test and fix for to_sym exception"
<code>
class Order < ActiveRecord::Base
  has_many :order_items, :foreign_key => :order_id
  accepts_nested_attributes_for :order_items
  attr_accessible :comment, :order_number, :order_items_attributes
end
class OrderItem < ActiveRecord::Base
  self.primary_keys = :order_id, :product_id
  belongs_to :order, :foreign_key => :order_id
  attr_accessible :order_id, :product_id, :quantity
end
</code>

when update

![editingorder](https://f.cloud.github.com/assets/486642/8087/f301d092-4461-11e2-9c6d-dd205704cb50.jpg)

Started PUT "/orders/1" for 127.0.0.1 at 2012-12-12 21:25:21 +0800
Processing by OrdersController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"cCDyF/fmu8zM4oGkIwdCH0Ya00rDe
HKUy8aPpX1k7XE=", <strong>"order"=>{"order_number"=>"123", "comment"=>"321", "order_item
s_attributes"=>{"0"=>{"order_id"=>"1", "product_id"=>"1", "quantity"=>"14", "_de
stroy"=>"false", "id"=>"[1, 1]"}}}, "commit"=>"Update Order", "id"=>"1"</strong>}
  [1m[35mOrder Load (0.0ms)[0m  SELECT "orders".\* FROM "orders" WHERE "orders
"."id" = ? LIMIT 1  [["id", "1"]]
  [1m[36m (0.0ms)[0m  [1mbegin transaction[0m
  [1m[35mOrderItem Load (1.0ms)[0m  <strong>SELECT "order_items".\* FROM "order_items"
 WHERE  "order_items"."order_id" = 1 AND "order_items"."order_id" = 0 AND "order_items"."product_id" IS NULL</strong>
  [1m[36m (0.0ms)[0m  [1mrollback transaction[0m
Completed 404 Not Found in 40ms

ActiveRecord::RecordNotFound (<strong>Couldn't find OrderItem with ID=[1, 1] for Order with ID=1</strong>):
  app/controllers/orders_controller.rb:62:in `block in update'
  app/controllers/orders_controller.rb:61:in`update'

source code in "http://github.com/wanweidong/cpk_accepts_nested_attributes_for"

**Comment by chrisbloom7** [comment]
I'm using CPK v5.0.14, which supposedly includes this patch, in a Rails 3.2.21 app, but I'm still getting this same error. 

    class AttributeGroup < ActiveRecord::Base
      self.primary_keys = :group_id, :attribute_id
    end

    [44, 53] in /Users/chrisbloom7/Project/app/controllers/admin/groups_controller.rb
       48:       debugger
    => 49:       if @group.update_attributes(params[:group])
    (byebug) params[:group][:attribute_groups_attributes]
    {"0"=>{"rank"=>"0", "_destroy"=>"false", "id"=>"[3, 2]"}}
    (byebug) @group.attribute_groups
    [#<AttributeGroup attribute_id: 2, group_id: 3, rank: 0>]
    (byebug) @group.attribute_groups.find("[3,2]")
    ActiveRecord::RecordNotFound Exception: Couldn't find AttributeGroup with ID=[3,2] WHERE `attribute_groups`.`group_id` = 3 AND `attribute_groups`.`group_id` = 0 AND `attribute_groups`.`attribute_id` = 2
nil
    (byebug) @group.attribute_groups.find("3,2")
    #<AttributeGroup attribute_id: 2, group_id: 3, rank: 0>

Did something regress in 5.0.14?

**Comment by cfis** [comment]
The discussion was about Rails 4.0, looks like you are having issues with Rails 3.2.   Each version of Rails is quite different, CPK has to be significantly rewritten with each version so its quite possible these are unrelated issues.  I'd say open a new ticket - but in reality you'll need to supply a patch since there isn't anyone to maintain such old versions of CPK (but I can apply a patch if you come up with one).
