### ISSUE TITLE
Rails 4.2 compatibility

### ISSUE THREAD

**Issue by jasonl99** [composite-primary-keys/composite_primary_keys#230]
Here's what I get when I specify rails 4.2.0beta1 in my gemfile

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    composite_primary_keys (>= 0) ruby depends on
      activerecord (~> 4.1.4) ruby

    rails (>= 4.2.0beta1) ruby depends on
      activerecord (4.2.0.beta1)

**Comment by cfis** [comment]
Going to close this in favor of # #326.
