### ISSUE TITLE
Somehow it messes pg JSON attribute

### ISSUE THREAD

**Issue by maca** [composite-primary-keys/composite_primary_keys#243]
I have a pg json attribute I defined in my migration as follows:
    

   create_table :identities do |t|
      ...
      t.json   :provider_response
   end

Prior to adding the gem I could update the attribute with a hash and get a hash back. When including the gem I get a string when reading the attribute. I've isolated all other changes.

**Comment by cfis** [comment]
Going to close this since its so old.
