### ISSUE TITLE
Rails 4.1.6 is not a symbol

### ISSUE THREAD

**Issue by jasonivers** [composite-primary-keys/composite_primary_keys#246]
I got an error when upgrading from 4.1.4 to 4.1.6, telling me that ["cpk_1", "cpk_2"] is not a symbol.

I fixed the error by changing

if self.composite? && attr == "id"

to

if self.composite? && (attr == "id" || attr == self.class.primary_key)

on line 5 of composite_primary_keys-7.0.10/lib/composite_primary_keys/active_model/dirty.rb

**Comment by CraneWing** [comment]
I'm getting this error on a table in Active Admin. Rails 4.2, ActiveRecord 4.2, composite_primary_keys 8.1.0.
