### ISSUE TITLE
Uniqueness validation with a condition fails

### ISSUE THREAD

**Issue by al2o3cr** [composite-primary-keys/composite_primary_keys#261]
https://github.com/rails/rails/pull/5321 added a `conditions` option to allow additional clauses to be appended to the query generated by `validates_uniqueness_of`.

The patched version here omits this feature, leading to bug reports like https://github.com/rails/rails/issues/17766 when users expect it to work.

The code from AR's version is directly portable here:
```ruby
relation = relation.merge(options[:conditions]) if options[:conditions]
```
right before the `exists?` call. Happy to write up a PR if needed.

**Comment by cfis** [comment]
Closing since this was fixed.
