### ISSUE TITLE
comparison of String with CompositePrimaryKeys::CompositeKeys failed

### ISSUE THREAD

**Issue by DVG** [composite-primary-keys/composite_primary_keys#276]
I have the following ActiveRecordModel (Rails 3.2)

```ruby
# Schema Information
# name            :string(255)
# a_string        :string(255)
# container_id :integer
#

class Account < ActiveRecord::Base
  self.primary_keys = :a_string, :container_id
  scope :name_is, ->(name) { where("UPPER(name) = ?", name.upcase) }
  validates_uniqueness_of :name, scope: [:container_id]
end
```

I'm attempting to test this scope using this simple spec and factory:

```
describe Account do
  describe "#name_is" do
    subject { create(:account, name: "BLAH") }
    it { expect(Account.name_is("blah")).to eq [subejct] }
  end
end

factory :account do
  a_string "foo"
  container_id 1
  name "bar"
end
```

When FactoryGirl tries to make an account, this happens:

```
Failure/Error: subject { create(:account, name: "BLAH") }
     ArgumentError:
       comparison of String with CompositePrimaryKeys::CompositeKeys failed
     # ./spec/models/account_spec.rb:5:in `block (3 levels) in <top (required)>'
     # ./spec/models/account_spec.rb:6:in `block (3 levels) in <top (required)>'
     # -e:1:in `<main>'
```

If I take out the primary key definition, everything works, but I'll lose the ability to build relationships off those primary keys. I can't really tell when it's comparing a string to the key definition.

I can, int he console, create an object, look it up using the composite key using find, and generally use it in a way that makes sense, it's just this spec that keeps blowing up. Where am I going wrong?

**Comment by cfis** [comment]
Sorry, not quite enough info there to help.  But clearly there is someplace in the test that is expecting a string but insteading getting a CPK array.
