### ISSUE TITLE
Error on local dev environment

### ISSUE THREAD

**Issue by dannio** [composite-primary-keys/composite_primary_keys#278]
I have come across a strange issue where when I use this on a production environment it's all fine but on my dev environment, I get:

    ["field1", "field2"] is not a symbol

The only dfference between dev and production is eager loading and caching classes, which when activated on Development enviroment still doesn't fix the issue...

Are there any known issues concerning this or does anyone have a solution?

This was an issue back in:
https://github.com/composite-primary-keys/composite_primary_keys/issues/246

And we are on version 7.0.11 which (we believe) is a version where we thought that this was already fixed...

**Comment by cfis** [comment]
Would need to have more context to help - what is the traceback you are seeing?

**Comment by cfis** [comment]
Closing this ticket - reopen if you have additional info you can provide.
