### ISSUE TITLE
create composite key in rails migration?

### ISSUE THREAD

**Issue by vmcilwain** [composite-primary-keys/composite_primary_keys#279]
Hello,

I am looking to use this gem but don't see anywhere on how to create a composite id in a rails migration so that migrates up and down with the db. Does this gem have that functionality or how would I execute the correct code using an sql statement in the migration?

Thanks,

**Comment by cfis** [comment]
There isn't any migration support.  But you can just use a sql migration.  The relevant sql will depend on your database.

**Comment by marnen** [comment]
Yuck, really? I haven't used this gem in ages, but I could swear I remember some sort of migration support. Was that removed, or do I misremember?

Perhaps I should think about adding migration support. SQL migrations are evil.

**Comment by FooBarWidget** [comment]
Active Record 5 supports creating primary keys in migrations (although it can't use them without the composite_primary_keys gem).

~~~ruby
create_table :states, id: false do |t|
  t.primary_keys [:repo, :pr_num]
  t.string :repo, null: false
  t.integer :pr_num, null: false
end
~~~

Executes:

~~~
DEBUG:    (11.9ms)  CREATE TABLE "states" ("repo" character varying NOT NULL, "pr_num" integer NOT NULL, PRIMARY KEY ("repo", "pr_num"))
~~~

**Comment by cfis** [comment]
Nice - good to know!
