### ISSUE TITLE
Partitioned table with multiple primary keys

### ISSUE THREAD

**Issue by jeyb** [composite-primary-keys/composite_primary_keys#280]
I have a partitioned table with multiple primary keys and I notice that from within the `after_create` block, the `id` attribute isn't set. Examples follow:
#### Table Schema

``` sql
CREATE TABLE `clicks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `delivery_id` int(11) NOT NULL,
  `delivery_created_at` datetime NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`,`delivery_created_at`),
  KEY `index_clicks_on_delivery_id_and_delivery_created_at` (`delivery_id`,`delivery_created_at`),
  KEY `index_clicks_on_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
/*!50500 PARTITION BY RANGE  COLUMNS(delivery_created_at)
(PARTITION p201306 VALUES LESS THAN ('2013-06-01') ENGINE = InnoDB) */
```
#### Model

``` ruby
class Click < ActiveRecord::Base
  self.primary_key = :id, :delivery_created_at

  after_create do |model|
    # puts model.inspect
    # <Click _id: nil, delivery_id: 1, delivery_created_at: "2015-01-29 23:48:39", created_at: "2015-01-29 23:48:39", updated_at: "2015-01-29 23:48:39">

    # puts model.id
    # [nil, Thu, 29 Jan 2015 15:48:39 PST -08:00]
  end
end
```

The object does get saved but the `id` attribute isn't set. I initially thought it was a collision between the `id` method and the attribute name, therefore, I renamed the column to `_id`, but the same issue occurred. Is this a known issue and do you know of any way to get around it?

This is being tested on Rails 4.1.6.

**Comment by cfis** [comment]
Hmm, probably something with the mysql driver.  Here is how the postgresql driver does it:

https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_4.1.x/lib/composite_primary_keys/connection_adapters/postgresql_adapter.rb#L4

**Comment by TheLastImperial** [comment]
I have the same issue using cpk 9.0.4, rails 5.0.0.1 and postgreSQL 9.5 
This happen in the `after_create` and in the `rails console`. I did the same that @jeyb change the name of my field `id` but didn't work.
When I updated to cpk 9.0.7 occur the issue #384
I check the cpk code  https://github.com/composite-primary-keys/composite_primary_keys/blob/7df5fe264ba1221b8b5dba52bedce599954def6c/lib/composite_primary_keys/connection_adapters/postgresql_adapter.rb#L42
and this method return correctly the cpk.
The code in rails that use the method `last_inserted_id` is 
https://github.com/rails/rails/blob/cdb307294a43eec489f0ea6ffdc6f0a07b16ff5c/activerecord/lib/active_record/connection_adapters/abstract/database_statements.rb#L125

I am not sure how to fix it.

**Comment by TheLastImperial** [comment]
I fix this bug by adding the method `_create_record` in the file [persistence](https://github.com/composite-primary-keys/composite_primary_keys/blob/v9.0.4/lib/composite_primary_keys/persistence.rb)

This method is the same that `activerecord` [_create_record](https://github.com/rails/rails/blob/cdb307294a43eec489f0ea6ffdc6f0a07b16ff5c/activerecord/lib/active_record/persistence.rb#L551)

I just added the condition: `self.id = new_id if composite?`.
The method is as follows:

```ruby
def _create_record(attribute_names = self.attribute_names)
  attributes_values = arel_attributes_with_values_for_create(attribute_names)
  new_id = self.class.unscoped.insert attributes_values
  self.id = new_id if composite?
  self.id ||= new_id if self.class.primary_key
  @new_record = false        
  id
end
```
