### ISSUE TITLE
ConnectionNotEstablished error when db connection is on class other than ActiveRecord::Base

### ISSUE THREAD

**Issue by wconrad** [composite-primary-keys/composite_primary_keys#283]
When a model's database connection is not via ActiveRecord::Base, and the model has a composite primary key, then the model raises "ActiveRecord::ConnectionNotEstablished".

# Versions

* composite_primary_key 7.0.13
* ruby-2.2.0
* active-record 4.1.9
* [oracle-enhanced-adapter HEAD c2d659](https://github.com/rsim/oracle-enhanced/commit/c2d65949799852b85a9479ec75dffeae33bd5bbf)

# What's this craziness about ActiveRecord::Base not having a connection?

I have a set of models that need to connect to a different database than the default Rails database.  These models are derived from an intermediate base class rather than directly from ActiveRecord::Base.

The intermediate base class:

```
module OpacsDb
  module Db
    # We establish the Opacs database connection on this class; that
    # connection is then shared by all the derived classes.
    class Base < ActiveRecord::Base
      self.abstract_class = true
    end
  end
end
```

A model:

```
module OpacsDb
  module Db
    class Org < Base
      self.table_name = "org"
      self.primary_key = [:or_customer, :or_rcc_code]
    end
  end
end
```

The connection is established with OpacsDb::Db::Base, e.g.

    OpacsDb::Db::Base.establish_connection(:opacs_test)

This works fine for any model which does not have a composite primary key.

Making a query using the the model having a composite primary key results in a stack trace:

```
> OpacsDb::Db::Org.count
ActiveRecord::ConnectionNotEstablished: ActiveRecord::ConnectionNotEstablished
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
/home/wayne/lab/composite_primary_keys/upstream/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:51:in `retrieve_connection'
/home/wayne/lab/composite_primary_keys/upstream/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:33:in `connection'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-5.0.1.20140414130214/lib/arel/tree_manager.rb:22:in `visitor'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/arel-5.0.1.20140414130214/lib/arel/tree_manager.rb:26:in `to_sql'
/home/wayne/lab/composite_primary_keys/upstream/lib/composite_primary_keys/relation/calculations.rb:38:in `execute_simple_calculation'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:227:in `perform_calculation'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:119:in `calculate'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.9/lib/active_record/relation/calculations.rb:34:in `count'
/home/wayne/.rvm/gems/ruby-2.2.0/gems/activerecord-4.1.9/lib/active_record/querying.rb:13:in `count'
/home/wayne/olio/opacs_db/lib/tasks/console.rake:15:in `block in <top (required)>'
/home/wayne/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/home/wayne/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

# Borrowing some code from activerecord-4.1.9 seems to fix it

There is some code in composite_primary_key's monkey patch of ActiveRecord::Relation::Calculations which, when replaced with some code from the same method in activerecord-4.1.9, seems to fix this issue.  The fix introduces no regressions in the composite_primary_key unit tests when run using either the sqlite3 or the postgresql adapter.  I can't say I truly understand what the code is doing, so it needs a more knowledgable eye to review it.  I'll submit a pull request shortly.

# Writing a unit test

A unit test for this will need to set up the situation I describe above, where ActiveRecord::Base has no connection, but a class between ActiveRecord::Base and the model does.  I'm not sure how to make the test framework do that.

**Comment by cfis** [comment]
Hi Wayne - Ok if that works, its fine with me since it brings the code in line with the latest ActiveRecord branch.  Can you submit a pull request?

**Comment by wconrad** [comment]
Thanks for doing the work on this.  I think that #284 merged in the fix.  Do you still need a pull request or anything else from me?

**Comment by cfis** [comment]
Yes, saw that after this comment.  Think we are good.
