### ISSUE TITLE
Extra query when eager loading and a column of the composite key is not selected

### ISSUE THREAD

**Issue by wconrad** [composite-primary-keys/composite_primary_keys#287]
If an active record query does not select all columns of the composite primary key, and the query eager-loads an association, then extra queries may be generated when accessing the accociation.

Given this schema:

```
  create_table "org", id: false, force: true do |t|
    t.integer  "n"
    t.string   "or_customer"
    t.string   "or_rcc_code"
    t.integer  "or_acct_mgr", precision: 38, scale: 0
  end

  create_table "salesman_names", id: false, force: true do |t|
    t.string "sm_code"
  end
```

With these models:

```
class Org < ActiveRecord::Base
  self.table_name = "org"
  self.primary_key = [:or_customer, :or_rcc_code]
  belongs_to :account_manager_1,
  'class_name': :SalesmanName,
  foreign_key: :or_acct_mgr,
  primary_key: :sm_code
end

class SalesmanName < ActiveRecord::Base
  self.table_name = "salesman_names"
  self.primary_key = :sm_code
end
```

And this data:

```
Org.create!([
    {n: 17, or_customer: "MEG", or_rcc_code: "ABC", or_acct_mgr: 204},
    {n: 18, or_customer: "MEG", or_rcc_code: "DEF", or_acct_mgr: 204},
  ])
SalesmanName.create!([
    {sm_code: 105},
    {sm_code: 204},
  ])
```

Then this code, which selects only part of the composite primary key:

```
orgs = Org.
  select(:or_customer).
  select(:or_acct_mgr).
  includes(:account_manager_1).
  order(:n)
orgs.each do |org|
  puts "Loading relation for #{org.attributes.inspect}:"
  org.account_manager_1
end
```

Causes these queries:

```
Org Load (0.1ms)  SELECT "org"."or_customer", "org"."or_acct_mgr" FROM "org"   ORDER BY "org"."n" ASC
SalesmanName Load (0.1ms)  SELECT "salesman_names".* FROM "salesman_names"  WHERE "salesman_names"."sm_code" IN (204)
Loading relation for {"or_customer"=>"MEG", "or_acct_mgr"=>204}:
Loading relation for {"or_customer"=>"MEG", "or_acct_mgr"=>204}:
SalesmanName Load (0.1ms)  SELECT  "salesman_names".* FROM "salesman_names"  WHERE "salesman_names"."sm_code" = 204 LIMIT 1
```

I did not expect activerecord to make the last query.

# Control experiment:

If the all columns of the primary key are selected:

```
orgs = Org.
  select(:or_customer).
  select(:or_rcc_code).    # Select added
  select(:or_acct_mgr).
  includes(:account_manager_1).
  order(:n)
orgs.each do |org|
  puts "Loading relation for #{org.attributes.inspect}:"
  org.account_manager_1
end
```

Then there is no extra query:

```
Org Load (0.1ms)  SELECT "org"."or_customer", "org"."or_rcc_code", "org"."or_acct_mgr" FROM "org"   ORDER BY "org"."n" ASC
SalesmanName Load (0.1ms)  SELECT "salesman_names".* FROM "salesman_names"  WHERE "salesman_names"."sm_code" IN (204)
Loading relation for {"or_customer"=>"MEG", "or_rcc_code"=>"ABC", "or_acct_mgr"=>204}:
Loading relation for {"or_customer"=>"MEG", "or_rcc_code"=>"DEF", "or_acct_mgr"=>204}:
```

# Versions

* composite_primary_keys (7.0.13)
* Ruby (2.2.0)
* activerecord (4.1.9)
* Any of these database drivers:
  * sqlite3 (1.3.10)
  * pg (0.18.1)
  * activerecord-oracle_enhanced-adapter (1.5.5)

# Gist

A self-contained program to reproduce the problem is [here][1]

[1]: https://gist.github.com/wconrad/d5d3ca522ac3c06e62fe

**Comment by cfis** [comment]
That is interesting.  Thanks for the gist - an excellent bug report.  Is this always duplicatable?  Meaning the first thing we will have to do is show the same thing happening with the test database to get it fixed (we could of course add your gist but I'm trying to slim down the test db since its already getting to big and sprawly).

**Comment by cfis** [comment]
I investigated this a bit more, and the reason is that in ActiveRecord, Preloader#preload does this:

      def preload(records, associations, preload_scope = nil)
        records       = Array.wrap(records).compact.uniq

If any records with a partial key match other records, only the first will make it through and the rest get eliminated.  So in your case the second record does not get the included record attached to it and runs a second query.  I see no obvious fix for this.  In the end everything works correctly, just not as efficiently as it could.  So closing this ticket.  Thanks for the heads-up.

**Comment by wconrad** [comment]
I suspected there might not be a reasonable fix for this.  It's a very "edge" behavior.  Thank you for investigating, and for the kind words about the bug report.  It's a lot of work to try to make a good bug report; I'm very glad you appreciated it.
