### ISSUE TITLE
CPK and Carrierwave

### ISSUE THREAD

**Issue by spscream** [composite-primary-keys/composite_primary_keys#292]
I have a model with mounted uploader on :photo field.
Then I update a record with new photo it raises an exception:

```
ActiveRecord::RecordNotFound: Couldn't find Debtloan with 'user_id,id'=["bbfb25f7-f906-41cf-8d6a-53c2e31b19fc"] [WHERE "debtloans"."deleted_at" IS NULL]

Stack trace (show Rails)
…/lib/composite_primary_keys/relation/
finder_methods.rb: 121:in `find_one'
…/lib/composite_primary_keys/relation/
finder_methods.rb:  93:in `find_with_ids'
…y_keys-268d671c8552/lib/composite_primary_keys/
core.rb:  32:in `find'
…2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/
mount.rb: 239:in `find_previous_model_for_photo'
…2.1.0/gems/carrierwave-0.10.0/lib/carrierwave/
mount.rb: 234:in `store_previous_model_for_photo'
```

this is a find_previous_model_for_photo method, from carrierwave:

``` ruby
def find_previous_model_for_#{column}
   self.class.find(to_key.first)
end
```

method to_key returns id of the record (e.g. [1,1]) not in Array.
This method is overrided by CPK in lib/composite_primary_keys/base.rb:

``` ruby
def to_key
   ids.to_a if !ids.compact.empty? # XXX Maybe use primary_keys with send instead of ids
end
```

But as described here: http://api.rubyonrails.org/classes/ActiveModel/Conversion.html#method-i-to_key
it should return Array of keys(e.g. [[1,1]]).

**Comment by thedanotto** [comment]
Did you ever figure this out? I'm having the same issue.

**Comment by cfis** [comment]
What version of ActiveRecord and CPK is this?
