### ISSUE TITLE
:verify_active_connections! removed

### ISSUE THREAD

**Issue by nextbyte** [composite-primary-keys/composite_primary_keys#294]
:verify_active_connections! was removed from Rails 4 but it is still referenced in connection_specification_changes.rb 

      delegate :clear_reloadable_connections!,
        :clear_all_connections!,:verify_active_connections!, :to => :connection_handler

Which causes errors with Spawnling for example which uses this:

ActiveRecord::Base.verify_active_connections! if ActiveRecord::Base.respond_to?(:verify_active_connections!)

ActiveRecord::Base.respond_to?(:verify_active_connections!) will return true because :verify_active_connections! is added in connection_specification_changes.rb

**Comment by cfis** [comment]
Ah, thanks.  Will remove.
