### ISSUE TITLE
has_many_through_association with polymorphic source

### ISSUE THREAD

**Issue by eproulx-petalmd** [composite-primary-keys/composite_primary_keys#299]
Hi,

Is there a way to verify composite? on scope instead of source_reflection in the has_many_through_association on delete_records (line 22)

My source_reflection isn't an ActiveModel, just a polymorphic association.

Thanks

**Comment by eproulx-petalmd** [comment]
target_scope would be the good one instead of scope. It's considering the source type which scope doesn't.

**Comment by cfis** [comment]
Can you put together a patch?

**Comment by cfis** [comment]
Going to close this - but please feel free to reopen.  An example would be very helpful.
