### ISSUE TITLE
ar_instance.id returns wrong id

### ISSUE THREAD

**Issue by wwalker** [composite-primary-keys/composite_primary_keys#303]
class Participant < ActiveRecord::Base
  self.primary_keys = :program_id, :id
2.2.1 :004 > p = ps[0]
 => #<Participant id: [164, 56216], program_id: 164, user_name: "grace", ....<snipped ridiculously long table  columns list> > 
2.2.1 :005 > p.id
 => [164, [164, 56216]] 

The actual database row value for id is 56216 and 164 is the program_id.

I would expect this to return [164, 56216].

**Comment by cfis** [comment]
Hmm, id has special meaning to ActiveRecord - it returns the key (whether a single key or composite key).  So what you are getting is actually what is expected.

**Comment by wwalker** [comment]
why am I getting program_id twice?   [ program_id [ program_id, id] ]
I would expect [program_id, id]

**Comment by cfis** [comment]
Because id returns [program_id, id].  ID represents the primary key as a whole, not an individual column.

Charlie
