### ISSUE TITLE
Doesn't work with accepts_nested_attributes_for on ar_3.2.x branch

### ISSUE THREAD

**Issue by chrisbloom7** [composite-primary-keys/composite_primary_keys#304]
Opening a new ticket as requested. I'm using CPK v5.0.14 in a Rails 3.2 app, which supposedly includes the patch listed in issue #141, but I'm still getting this same error. 

    class AttributeGroup < ActiveRecord::Base
      self.primary_keys = :group_id, :attribute_id
    end

    [44, 53] in /Users/chrisbloom7/Project/app/controllers/admin/groups_controller.rb
       48:       debugger
    => 49:       if @group.update_attributes(params[:group])
    (byebug) params[:group][:attribute_groups_attributes]
    {"0"=>{"rank"=>"0", "_destroy"=>"false", "id"=>"[3, 2]"}}
    (byebug) @group.attribute_groups
    [#<AttributeGroup attribute_id: 2, group_id: 3, rank: 0>]
    (byebug) @group.attribute_groups.find("[3,2]")
    ActiveRecord::RecordNotFound Exception: Couldn't find AttributeGroup with ID=[3,2] WHERE `attribute_groups`.`group_id` = 3 AND `attribute_groups`.`group_id` = 0 AND `attribute_groups`.`attribute_id` = 2
    nil
    (byebug) @group.attribute_groups.find("3,2")
    #<AttributeGroup attribute_id: 2, group_id: 3, rank: 0>

Did something regress in 5.0.14? I know this is an old branch, but we are in the middle of an upgrade from Rails 2.3 -> 4.x, and 3.2 is a mid-upgrade stopping place for us so this is critical for us. Happy to contribute a fix if you can point me in the right direction.

See also: #63, #134

**Comment by cfis** [comment]
Sorry for the late response on this.  Is this still an issue?

**Comment by cfis** [comment]
Going to close since this is on a no longer supported branch.
