### ISSUE TITLE
Not a symbol.

### ISSUE THREAD

**Issue by CraneWing** [composite-primary-keys/composite_primary_keys#313]
I am using CPK so that I can edit a join table in Active Admin. I have a table category_recipes, with two columns, recipe_id and category_id. This is the model I am using for the table's index page in Active Admin.

```ruby
require 'composite_primary_keys'

ActiveAdmin.register CategoryRecipe do
   
   form do |f|
      f.semantic_errors
      inputs 'Catgory Recipes' do
         input :category_id
         input :recipe_id
      end
      f.submit
   end
   
   remove_filter :category
   remove_filter :recipe
   
   permit_params :category_id, :recipe_id
end
```
My exact error is **["category_id", "recipe_id"] is not a symbol**.

The error is being thrown in Active Admin's display_helper, in this block:

```ruby
    module DisplayHelper

      DISPLAY_NAME_FALLBACK = ->{

        name, klass = "", self.class
        name << klass.model_name.human         if klass.respond_to? :model_name
        name << " ##{send(klass.primary_key)}" if klass.respond_to? :primary_key
        name.present? ? name : to_s

      }
```
Using Rails 4.2, ActiveRecord 4.2, composite_primary_keys 8.1.0.

**Comment by cfis** [comment]
You have to setup the model to have a composite key.  That is generally done like this:

class MyClass
  self.primary_keys = [:id1, :id2]
end

**Comment by CraneWing** [comment]
I have that exactly in my code, as the documentation says, but I still get the error.

**Comment by IMhide** [comment]
I had the exact same error. I simply fixed the issues by overriding the primary_key method this way :
```   
def self.primary_key
    super.to_s
end
```
