### ISSUE TITLE
SQL Server: CPK 8.1.0 and activerecord-sqlserver-adapter 4.2.4 generate wrong SQL in some queries on tables without a DB primary key

### ISSUE THREAD

**Issue by bunyan** [composite-primary-keys/composite_primary_keys#316]
If I have a table with no primary key in DB defined like this:

``` ruby
create_table :no_id_models, id: false do |t|
      t.integer :pk1
      t.integer :pk2
    end
```

and a corresponding model with CPK

``` ruby
class NoIdModel < ActiveRecord::Base
  self.primary_keys = [:pk1, :pk2]
end
```

Calling

``` ruby
NoIdModel.limit(1).to_a
```

will result in the following error:

```
TinyTds::Error: Invalid column name 'pk1,pk2'.: EXEC sp_executesql N'SELECT  [no_id_models].* FROM [no_id_models]  ORDER BY [no_id_models].[pk1,pk2] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
```

I actually faced this with a belongs_to association but this is a simpler case. 

In make_Fetch_Possible_And_Deterministic (/activerecord-sqlserver-adapter-4.2.4/lib/arel/visitors/sqlserver.rb:142), the adapter gets the composite key for a table and applies the sorting order to the whole "array" key which then results in wrong SQL. It's hardly a bug of the sqlserver-adapter so I'm posting it here.

To make things work for me I overrode the method in a Rails initializer to expand the query:

``` ruby
module SQLServerCPKOrderFix
  def make_Fetch_Possible_And_Deterministic o
    super
    o.orders.each_with_index do |node, i|
      rel = node.expr.relation
      expr_name = node.expr.name
      if expr_name.is_a?(CompositePrimaryKeys::CompositeKeys)
        o.orders[i] = expr_name.collect { |a| rel[a].send(node.direction) }
      end
    end
  end
end

Arel::Visitors::SQLServer.prepend(SQLServerCPKOrderFix)
```

Not sure how to incorporate this into the gem though.

A gist that reproduces the bug: https://gist.github.com/bunyan/1ea31f8b6ce8290c50b6

**Comment by cfis** [comment]
Look at the connection_adapters folder - that's where we put overrides to ActiveRecord connection adapters.  So could the adapter be fixed instead?

**Comment by ckoch-ncsa** [comment]
In a project with composite_primary_keys (cpk), we experienced a similar error. It was noticeable when calling MODEL.reload. It would incorrectly form primary keys in order by, like [MODEL][pk1, pk2]. In order to make it work, we used code suggested by @bunyan from above, but we patched the gem method make_Fetch_Possible_And_Deterministic directly. (the difference is that it gets run only when o.orders are empty and this worked for us)

```ruby    
def make_Fetch_Possible_And_Deterministic o
  return if o.limit.nil? && o.offset.nil?
  t = table_From_Statement o
  pk = primary_Key_From_Table t
  return unless pk
  if o.orders.empty?
    # Prefer deterministic vs a simple `(SELECT NULL)` expr.
    o.orders = [pk.asc]
    o.orders.each_with_index do |node, i|
      rel = node.expr.relation
      expr_name = node.expr.name
      if expr_name.is_a?(CompositePrimaryKeys::CompositeKeys)
        o.orders[i] = expr_name.collect { |a| rel[a].send(node.direction) }
      end
    end
  end
end

```

We found that the first time the query was loaded the cpks were rendered in a way that worked for the query:
[MODEL][pk1], [MODEL][pk2]
but on the reload, the primary_keys were empty.

**Comment by vladhadzhiyski** [comment]
Has anyone been able to fix or come up with a more straight forward solution than monkey patching things? 

I'm also running into this same issue:

```
ActiveRecord::StatementInvalid: TinyTds::Error: Invalid column name '"ShopID", "UserID"'.: EXEC sp_executesql N'SELECT  [NHIF_Patients].* FROM [NHIF_Patients] WHERE [NHIF_Patients].[PatEGN] = @0  ORDER BY [NHIF_Patients].["ShopID", "UserID"] ASC OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 varchar(10), @1 int', @0 = '5812236053', @1 = 1
```

**Comment by cfis** [comment]
For what its worth, the latest release has the best sql servers support CPK has ever had. But it does require Active Record 6.

For old CPK releases that are no longer supported, yes, just make a monkey patch. Feel free to submit a patch and it can be integrated in if tests pass.

**Comment by ikak0nek0chanpanda** [comment]
Now i use the latest release CPK(13), activerecord-sqlserver-adapter 6.1.0.0.rc1, active record6.1.3.1 
but, i'm also runnning into this same issue:

EXEC sp_executesql N'SELECT [due_balances].* FROM [due_balances] ORDER BY [due_balances].["id_account", "due_date"] ASC OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 1  [["LIMIT", nil]]
Traceback (most recent call last):
        1: from (irb):1
ActiveRecord::StatementInvalid (TinyTds::Error: Invalid column name '"id_account", "due_date"'.)

The monkey patch above also doesn't work.
Does anyone know a solution?

**Comment by codeodor** [comment]
Can you show the full stack trace?

**Comment by ikak0nek0chanpanda** [comment]
@codeodor 
this is full stack trace.

["/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:447:in `each'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:447:in `handle_to_names_and_values_dblib'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:438:in `handle_to_names_and_values'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:417:in `_raw_select'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:412:in `block in raw_select'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activesupport-6.1.3.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:412:in `raw_select'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:307:in `sp_executesql'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-sqlserver-adapter-6.1.0.0.rc1/lib/active_record/connection_adapters/sqlserver/database_statements.rb:37:in `exec_query'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:536:in `select_prepared'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/database_statements.rb:67:in `select_all'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/connection_adapters/abstract/query_cache.rb:103:in `select_all'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/querying.rb:47:in `find_by_sql'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:849:in `block in exec_queries'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:867:in `skip_query_cache_if_necessary'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:834:in `exec_queries'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:638:in `load'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:249:in `records'",
 "/.../vendor/bundle/ruby/2.5.0/gems/activerecord-6.1.3.1/lib/active_record/relation.rb:244:in `to_ary'", "(pry):1:in `<main>'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `eval'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:387:in `evaluate_ruby'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:355:in `handle_line'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:274:in `block (2 levels) in eval'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `catch'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:273:in `block in eval'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `catch'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_instance.rb:272:in `eval'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:77:in `block in repl'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `loop'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:67:in `repl'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `block in start'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:59:in `__with_ownership'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/input_lock.rb:77:in `with_ownership'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:38:in `start'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/repl.rb:13:in `start'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-0.12.2/lib/pry/pry_class.rb:200:in `start'",
 "/.../vendor/bundle/ruby/2.5.0/gems/pry-byebug-3.8.0/lib/pry-byebug/pry_ext.rb:13:in `start_with_pry_byebug'",
 "/.../vendor/bundle/ruby/2.5.0/gems/railties-6.1.3.1/lib/rails/commands/console/console_command.rb:70:in `start'",
 "/.../vendor/bundle/ruby/2.5.0/gems/railties-6.1.3.1/lib/rails/commands/console/console_command.rb:19:in `start'",
 "/.../vendor/bundle/ruby/2.5.0/gems/railties-6.1.3.1/lib/rails/commands/console/console_command.rb:102:in `perform'",
 "/.../vendor/bundle/ruby/2.5.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'",
 "/.../vendor/bundle/ruby/2.5.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'",
 "/.../vendor/bundle/ruby/2.5.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'",
 "/.../vendor/bundle/ruby/2.5.0/gems/railties-6.1.3.1/lib/rails/command/base.rb:69:in `perform'",
 "/.../vendor/bundle/ruby/2.5.0/gems/railties-6.1.3.1/lib/rails/command.rb:50:in `invoke'",
 "/.../vendor/bundle/ruby/2.5.0/gems/railties-6.1.3.1/lib/rails/commands.rb:18:in `<top (required)>'", "bin/rails:4:in `require'", "bin/rails:4:in `<main>'"]
