### ISSUE TITLE
composite primary keys and carrierwave

### ISSUE THREAD

**Issue by thedanotto** [composite-primary-keys/composite_primary_keys#317]
Hey guys, forgive me, I'm a bit new at trying to contribute to open source projects.

I'm running into an error when using composite primary keys in conjunction with carrierwave. I asked for help on stackoverflow, but didn't receive much fanfare. I'd like to fix the problem, but need some help getting started.

What are my options? Do I post a description of the error here? Do I write some code and do a pull request? I'm not even sure if I should be contacting you guys or carrierwave.

Any help is greaaaatly appreciated.

**Comment by deevis** [comment]
Posting with a description of the problem would be at least a couple orders of magnitude more helpful than posting without a description of the problem :)

Seriously, though - this *is* the place to describe the problem and provide code samples to demonstrate it.

However, it's not the place to have a forum discussion...

So now I'm out of line...

DOH!

**Comment by cfis** [comment]
Either include a link to your stackoverflow post or post the issue here.
