### ISSUE TITLE
has_one relationship resulting in type error

### ISSUE THREAD

**Issue by toddwf** [composite-primary-keys/composite_primary_keys#318]
ruby 2.0.0p247 
rails 4.2.1
cpk 8.1.1  (and exists in 8.1.0)

I have a cpk has_one relationship, when I save the record, I get a type_error:
TypeError ([:cpk1, :cpk2] is not a symbol):

When I change to has_many, the problem goes away.
Code:
	has_one :table_a, :primary_key => [:cpk1, :cpk2 ] , :foreign_key => [:cpk1, :foreign_key_cpk2]

There's no trace in the dev web server that looks meaningful.

Anyone else seen this?

**Comment by ismith** [comment]
Trace is probably meaningful where it enters ActiveRecord.

**Comment by cfis** [comment]
Going to close.  If you would like to reopen please provide more information (like ismith said, a traceback at a minimum).
