### ISSUE TITLE
Removal of Column#primary in 4.2.4 causes ActiveRecord to sometimes set primary keys on create

### ISSUE THREAD

**Issue by pdg137** [composite-primary-keys/composite_primary_keys#323]
[This Rails commit](https://github.com/rails/rails/commit/05dd3df35db8b2d39ed177f4ccfe112bdfe7726d) removed the method `Column#primary`, which unsurprisingly causes some trouble with this gem. Is it working for most people on Rails 4.2.4?

In particular, the change to the definition of `pk_attribute?` looks like it is incompatible with  composite_primary_keys, and for me it results in ActiveRecord trying to write NULL to a primary key - but only when saving a `dup`ed object. I will try to submit some tests and a suggested fix later.

**Comment by brgaulin** [comment]
@pdg137 I would love to see some tests for this. I had heard of some werid rails4.2.4 stuff with this gem and was looking to contribute =) The only time I see this gem explicitly use the .primary call is in model_schema.rb, but yes that change does seem alarming. I will have to poke and prod for anywhere we use the column to determine primary_key which sounds like a fun one

**Comment by cfis** [comment]
Is this fixed with brgaulin's commit?

**Comment by cfis** [comment]
Looks to me it is since all tests pass.  Closing.

**Comment by brgaulin** [comment]
Did this get merged?
On Sun, Dec 13, 2015 at 10:43 PM Charlie Savage <notifications@github.com>
wrote:

> Looks to me it is since all tests pass. Closing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/composite-primary-keys/composite_primary_keys/issues/323#issuecomment-164334181>
> .
>
-- 
--
Brendan Gaulin

**Comment by cfis** [comment]
You mean your commits?  45a8f44f5ceaad67f97ca676d8266df57cea4261 and 515f2722686f6b47aa2450ba5a5e84ed67b4fbe9?  Yes a couple of months ago.

**Comment by brgaulin** [comment]
Solid. Totally forgot lol. Thanks!
On Sun, Dec 13, 2015 at 10:57 PM Charlie Savage <notifications@github.com>
wrote:

> You mean your commits? 45a8f44
> <https://github.com/composite-primary-keys/composite_primary_keys/commit/45a8f44f5ceaad67f97ca676d8266df57cea4261>
> and 515f272
> <https://github.com/composite-primary-keys/composite_primary_keys/commit/515f2722686f6b47aa2450ba5a5e84ed67b4fbe9>?
> Yes a couple of months ago.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/composite-primary-keys/composite_primary_keys/issues/323#issuecomment-164335880>
> .
>
-- 
--
Brendan Gaulin

**Comment by cfis** [comment]
Still a tree, but without the grouping nodes.  So the tree should be half the size.  Sure would be nice if there was a OR predictate that took any # of predicates but I don't think Arel has such a thing.

**Comment by brgaulin** [comment]
I can pull your commit down this week and try it. See if our app that does
massive ors is ok. :) since AR does like 2 or 5 thousand by default those
should be our targets. We do I think 500 in that app.
On Sun, Dec 13, 2015 at 10:59 PM Charlie Savage <notifications@github.com>
wrote:

> Still a tree, but without the grouping nodes. So the tree should be half
> the size. Sure would be nice if there was a OR predictate that took any #
> of predicates but I don't think Arel has such a thing.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/composite-primary-keys/composite_primary_keys/issues/323#issuecomment-164336064>
> .
>
-- 
--
Brendan Gaulin

**Comment by cfis** [comment]
Sounds like a plan.
