### ISSUE TITLE
Any prevision of support for Active Record 5.0?

### ISSUE THREAD

**Issue by Kalunia** [composite-primary-keys/composite_primary_keys#332]
Hi, about Rails 5 arriving in the coming days, when can we expect the gem to support the Active Record 5.0? There are already some codes, issues and discussions rolling?

I would know too if is much complicated to make the adjusts in order to adapt to the new Active Record. Maybe we could help with some contribution and make this gem available for the newest rails version!

Thanks for the attention!

**Comment by cfis** [comment]
Sorry for the delay.  The master branch has changes to support Rails 5.  I haven't had a chance to verify them, so haven't released a gem yet.  

If you have time, that would be quite helpful to check them.

**Comment by dreyks** [comment]
The master branch still requests 'activerecord', '~> 4.2.0' in gemspec

**Comment by jmonteiro** [comment]
Confirmed, trying to install it with Rails 5.0.0.beta2 renders the following:

```
jmonteiro@pc ~/C/rails5project> bundle
Fetching git://github.com/composite-primary-keys/composite_primary_keys.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 5.0.0.beta2)

  In Gemfile:
    composite_primary_keys was resolved to 8.1.1, which depends on
      activerecord (~> 4.2.0)

    paper_trail was resolved to 4.0.1, which depends on
      activerecord (< 6.0, >= 3.0)

    rails (< 5.1, >= 5.0.0.beta2) was resolved to 5.0.0.beta2, which depends on
      activerecord (= 5.0.0.beta2)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by cfis** [comment]
Sorry I was mistaken.  Ok, updated the gem file.  And updated the finder methods.  But still a long way to go, patches welcome.  Use the master branch.

**Comment by cfis** [comment]
See #348 and master branch.
