### ISSUE TITLE
History.rdoc is out of date (missing version 8.1.2)

### ISSUE THREAD

**Issue by jgandt** [composite-primary-keys/composite_primary_keys#333]
I'm updating my gems and as I crawl through changelogs I noticed that the `History.rdoc` does not have the latest version included (version 8.1.2).

I assume this is safe because it is just a point release, but I always prefer to see exactly what changed.

I don't see any contribution guidelines, so I apologize if this is SOP. I will attempt to put the documentation together. Yet I expect that someone in the trenches of this project is better suited to update it.

Thanks for all the good work! It is appreciated!

**Comment by cfis** [comment]
Its on the 4.2 branch.

https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_4.2.x/History.rdoc
