### ISSUE TITLE
How to update composite key table.

### ISSUE THREAD

**Issue by sarbadaj** [composite-primary-keys/composite_primary_keys#336]
self.primary_keys = :id,:category

**Comment by cfis** [comment]
What is your question?

**Comment by sarbadaj** [comment]
How to update table having composite key in rails
<Address:0x0000000ab499c0
 id: [1003, "group"],
 user_id: 1,
 society_id: 2,
 category: "group",
 latitude: -33.817,
 longitude: 151.2008,
 country_name: "Australia",
 city: "Naremburn",
 country_code: "AU",
 region_code: "NSW",
 region_name: "New South Wales",
 zip_code: "2065",
 time_zone: "Australia/Sydney",
 metro_code: "0",
 created_at: Fri, 11 Mar 2016 05:56:54 UTC +00:00,
 updated_at: Fri, 11 Mar 2016 05:56:54 UTC +00:00,
 street: "Quiamong Road",
 group_id: 203>

**Comment by cfis** [comment]
Still not sure about you question, sorry.
