### ISSUE TITLE
Passing a nested array to Active Record finder methods is deprecated

### ISSUE THREAD

**Issue by yhirano55** [composite-primary-keys/composite_primary_keys#338]
Rails 4.2.5.1 has deprecated `Passing a nested array` [see here](https://github.com/rails/rails/blob/v4.2.5.1/activerecord/lib/active_record/relation/predicate_builder/array_handler.rb#L3)

```
DEPRECATION WARNING: Passing a nested array to Active Record finder methods is deprecated and will be removed. Flatten your array before using it for 'IN' conditions. (called from lib/composite_primary_keys/relation/predicate_builder.rb:32)
```

[predicate_builder.rb:32](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/relation/predicate_builder.rb#L32)

**Comment by cfis** [comment]
Ok, does this cause any issues or you just get deprecation warnings?  More inclined to fix in the Rails 5. branch.

**Comment by cfis** [comment]
Going to close this since haven't heard back.
