### ISSUE TITLE
undefined method `convert_value_to_association_ids'

### ISSUE THREAD

**Issue by donovan-duplessis** [composite-primary-keys/composite_primary_keys#339]
Hi There,

I have implemented this gem in 2 models, but since I have started using it, I am getting this error randomly saving throughout the framework.  I am running rails 4.2.0 (activerecord 4.2.0) and composite_primary_keys 8.1.2.  I am also using Mysql.  Any ideas?

NoMethodError in Backend::AccountsController#update
undefined method `convert_value_to_association_ids' for ActiveRecord::PredicateBuilder:Class

Extracted source (around line #24):

        if base_class && !(Base === value && value.composite?)
          primary_key = reflection.association_primary_key(base_class)
          value = convert_value_to_association_ids(value, primary_key)
        end
      end

Application Trace | Framework Trace | Full Trace
composite_primary_keys (8.1.2) lib/composite_primary_keys/relation/predicate_builder.rb:24:in `expand'
activerecord (4.2.0) lib/active_record/relation/predicate_builder.rb:43:in `block in build_from_hash'
activerecord (4.2.0) lib/active_record/relation/predicate_builder.rb:21:in `each'
activerecord (4.2.0) lib/active_record/relation/predicate_builder.rb:21:in `build_from_hash'
activerecord (4.2.0) lib/active_record/relation/query_methods.rb:958:in `build_where'
activerecord (4.2.0) lib/active_record/relation/query_methods.rb:584:in `where!'
composite_primary_keys (8.1.2) lib/composite_primary_keys/associations/has_many_through_association.rb:25:in `delete_records'

Regards,
Donovan

**Comment by donovan-duplessis** [comment]
Hi There,

I think I found the issue my side.  I'm just hoping that you can confirm it for me:

`
class Account < ActiveRecord::Base
  has_many :account_countries
  has_many :countries, -> { order(:name) }, through: :account_countries,
    dependent: :destroy
end
`

`
class Country < ActiveRecord::Base
  has_many :account_countries
  has_many :accounts, -> { order(:name) }, through: :account_countries,
    dependent: :destroy
  has_many :vat_entries
  has_many :vat_entries, through: :account_countries
end
`

`
class AccountCountry < ActiveRecord::Base
  self.primary_keys = :account_id, :country_id

  belongs_to :account
  belongs_to :country

  has_many :vat_entries, :class_name => 'VatEntry',
    foreign_key: [ :account_id, :country_id ]
end
`

I see I had an extra has_many :vat_entries association defined in the country model by mistake.  And possibly at random stages in using the application, the composite keys gem was using this incorrect association and calling convert_value_to_association_ids on it which was breaking?  I hope so!  It is quite critical I nail this.

Thanks again for this excellent gem which I use in my Rails 3 projects.  This current project is in Rails 4.

Regards,
Donovan

**Comment by jufemaiz** [comment]
Can you confirm that this resolved it?

I'm getting errors too though from digging into the code it looks more like a polymorphic association causing the problems.

```
undefined method `convert_value_to_association_ids' for ActiveRecord::PredicateBuilder:Class

     # /Users/***/.rvm/gems/ruby-2.0.0-p645@***/gems/composite_primary_keys-8.1.2/lib/composite_primary_keys/relation/predicate_builder.rb:24:in `expand'
```

https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_4.2.x/lib/composite_primary_keys/relation/predicate_builder.rb#L24

**Comment by cfis** [comment]
Donovan, if it works for you then that sounds good.
jufemaiz try the latest gem and if you still have an issue go ahead and open a ticket with a bit more info (traceback and even better a test case).
