### ISSUE TITLE
model_instance.reload undefined method error

### ISSUE THREAD

**Issue by rand99** [composite-primary-keys/composite_primary_keys#349]
I'm getting an error when I call reload
rails version 4.2.6
composite-primary-keys 8.1.2
 
     model_instance.reload
     *** NoMethodError Exception: undefined method `length' for 2:Fixnum

**Comment by rand99** [comment]
UPDATE:

this issue only occurs when 
one of the composite_primary_keys is called id

looks like non of the keys should be named 'id'

**Comment by cfis** [comment]
Yes, that is correct. I have seen patches to support having a key called .id, but then what does .id mean?  The full key or just one field in the key?
