### ISSUE TITLE
Wrong caching of associated habtm records before save

### ISSUE THREAD

**Issue by alexkuebo** [composite-primary-keys/composite_primary_keys#351]
In CPK 7.0.16 on Rails 4.1.15 I've got a simple model like this:

```
class Example < ActiveRecord::Base
   has_and_belongs_to_many :kind
end
```
Now the following code results in an error:
```
e = Example.new
e.kind_ids = [1, 2, 3]
e.kind_ids = [1, 2]
e.save
```
because it insert kind_id = 3 in the habtm table.
Without loading composite_primary_keys everythings works as expected.

**Comment by cfis** [comment]
Seems to work fine here, see:

c381348ad06bda3f13ecb6854a341b51cb95a2af

**Comment by alexkuebo** [comment]
Thank you very much for the test case, but it seems to happen only with a new object.

When modifying the test like this:
`employee = Employee.new`
`employee.group_ids = [1, 2]`
`employee.group_ids = [1]`
`employee.save`
`employee.reload`
`assert_equal(employee.group_ids.length, 1)`
it fails.

Could someone please have a look at this?
