### ISSUE TITLE
why a subquery is needed Model.count ?

### ISSUE THREAD

**Issue by dreyks** [composite-primary-keys/composite_primary_keys#353]
Having a model with a CPK `Model.count` expands into something like
```
SELECT COUNT(count_column) FROM (SELECT 1 AS count_column FROM `db`.`model`) subquery_for_count
```
which is times slower than a simple 
```
SELECT COUNT(*) FROM `db`.`model`
```
without CPK

Why is this subquery needed?

**Comment by cfis** [comment]
That's active record doing it.  See:

def ActiveRecord::Calculations#build_count_subquery(relation, column_name, distinct)

Could be CPK is triggering that method and it could be optimized for the :all column case.  Happy to take a patch.
