### ISSUE TITLE
update_all error introduced in 8.1.3

### ISSUE THREAD

**Issue by dahlb2** [composite-primary-keys/composite_primary_keys#359]
error does not exist in version 8.1.2 but happens in 8.1.3.

Model.update_all({phone_number: '5555550100'})

NoMethodError:
       undefined method `map' for "id":String
     # /ruby-2.1.6/gems/composite_primary_keys-8.1.3/lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb:18:in`subquery_for'
     # /gems/ruby-2.1.6/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:334:in `join_to_update'
     # /gems/ruby-2.1.6/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:342:in`join_to_update'
     # /gems/ruby-2.1.6/gems/activerecord-4.2.6/lib/active_record/relation.rb:337:in `update_all'
     # /gems/ruby-2.1.6/gems/activerecord-4.2.6/lib/active_record/querying.rb:8:in`update_all'
     # ./lib/tasks/prod_replication.rake:27:in `block (3 levels) in <top (required)>'

**Comment by cfis** [comment]
How about in 8.1.4?

**Comment by dahlb2** [comment]
yeah still same error happening in 8.1.4

**Comment by scambra** [comment]
Me too

**Comment by cfis** [comment]
Hmm, I can't duplicate.  I updated the test in f8b62e1.  Can you duplicate with a test?

**Comment by jmatsuba** [comment]
Still and issue for our project as well.

**Comment by cfis** [comment]
Happy to take a pull request, but closing since Rails core team no longer supports Rails 4.2
