### ISSUE TITLE
find_in_batches does not scale

### ISSUE THREAD

**Issue by timanovsky** [composite-primary-keys/composite_primary_keys#360]
Did you try to use `find_in_batches` on large tables? It does not scale. After first few hundred thousands records it slows down to dead. One query taking few seconds. The problem is with the `OR` query, as far as I understand. `WHERE (PK1 > x) OR ((PK1=x) AND (PK2>y))`. I'm using Postgres. I replaced `find_in_batches` with custom query using SQL row values and it works much better, query time is a constant now: `WHERE (PK1, PK2)  > (x, y) ORDER BY PK1 ASC, PK2 ASC`

**Comment by codeodor** [comment]
@timanovsky is there any chance you could help this out by providing more info, such as Rails + CPK versions, generated data that exhibits the problem, and benchmarks that show the time differences (and specs of computer you ran it on)?

I think this is fixable -- worst case as you mention could be to support this syntax for PG and fall back to the other for other DBs -- but I think without the additional info, I'd be running around not knowing if what I did had any effect.

Thanks!

**Comment by cfis** [comment]
Going to close since we didn't get feedback...happy to reopen with more info.
