### ISSUE TITLE
Release 9.0.0 since Rails 5 is out now

### ISSUE THREAD

**Issue by codeodor** [composite-primary-keys/composite_primary_keys#362]
I retested the master branch (mysql, sqlite3, and postgresql) against Rails 5 and everything comes back good in my app and in the CPK tests.

**Comment by cmager** [comment]
rails version: `5` (upgraded from 4.2.6)
ruby: `2.3.1`
adapter: `postgresql (pg 0.18.4)`

I am receiving this error. Any ideas what needs to be fixed?

```
[...]/gems/activerecord-5.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:840:in `establish_connection': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from [...]/bundler/gems/composite_primary_keys-9ff65e55df48/lib/composite_primary_keys/connection_adapters/abstract/connection_specification_changes.rb:25:in `establish_connection'
```

**Comment by codeodor** [comment]
@cmager thanks for the info. I can't check now, but I should be able to try it out tomorrow when I get back to the computer.

Any chance you can give a little more info in the mean time, about what the line in your app is trying to do at this point of failure? (I think there's probably enough info already, but a little more might be helpful just in case)

**Comment by cmager** [comment]
Hi, I basically updated the Gemfile to meet all rails 5.0.0 dependencies, copied config/*, config/initializers/* from a fresh rails 5 project and made adjustmetns.

Then I’m doing a `rails c` or `rails s`. That’s when the error happens.
I’ll try to give more feedback later this evening (CET).

**Comment by cfis** [comment]
codeodor - let me know once you have a chance to review.  I can then cut a new gem.

Also, is this one fixed?  #356.

Charlie

**Comment by codeodor** [comment]
@cfis good call on pointing out that other issue. I think #357 which fixes it also fixes this one, because it looks like this is the same line in question. 

![image](https://cloud.githubusercontent.com/assets/23479/16634593/1045320e-4394-11e6-8989-4f65ff4a95f0.png)

Furthermore, as @cmager's stack trace coupled with my screenshot above shows, @cmager is one commit behind that fix.

My app and the tests I ran are on d1d05ef9a6485b92c1fe17ca9291632e71e387bf, and everything looks good. I've been running my app in production on this commit from CPK for a couple of days now with no issue. (Not that I exercise all of CPK, but certainly it boots, unlike what is described in this issue).

@cmager  I think if you `bundle update composite-primary-keys` you'll get the latest version and it will be resolved.

@cfis I also think it's OK to release now, assuming I'm right about the above.

**Comment by cfis** [comment]
Released.  Thanks for doing all the hard work @codeodor!

**Comment by djantzen** [comment]
It's working for us now. Thank you guys!
