### ISSUE TITLE
Primary keys not set after create

### ISSUE THREAD

**Issue by kirillsalykin** [composite-primary-keys/composite_primary_keys#365]
```
class Rec < ApplicationRecord
  self.primary_keys = [:seq, :status]
end

rec = Rec.create
rec.id # => [nil, nil]
```

`req` - is sequential integer, eg database sets default value.

Rails uses ||= for setting generated ids 
```
self.id ||= new_id if self.class.primary_key
```
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/persistence.rb#L560

Id for transient record is [nil, nil], thus it will be never overwritten with values from db.

**Comment by cfis** [comment]
Yeah, I think you'll need to do this by hand in your application code.  I guess CPK could check each primary key's type, determine if its a serial, and if yes fill in the value.  But this issue has never come up before so I'm guessing this is fairly unusual case.
