### ISSUE TITLE
It breaks find_or_create_by

### ISSUE THREAD

**Issue by astropanic** [composite-primary-keys/composite_primary_keys#366]
**To reproduce:**

If you're using composite primary keys like 

``` ruby
class Foo < ActiveRecord::Base
  self.primary_keys = :bar, :baz
end
```

Then the 'find_or_create_by' method with a passed block doesn't update the attributes of the model.

``` ruby
Foo.destroy_all
Foo.create(bar: 1, baz: 2, fuzz: 666)

Foo.find_or_create_by(bar: 1, baz: 2) do |record|
  record.fuzz = 123
end

Foo.first.fuzz
```

You will get the old value `666` instead of the updated `123`

**Expected behavior:**

The passed block is correctly evaluated, and the attributes are updated.

**Comment by artm** [comment]
from rails documentation:

> This method accepts a block, which is passed down to create. 

I.e. it is only evaluated with the new records, not with existing ones like in your example.

**Comment by cfis** [comment]
Thanks artm for looking into this.
