### ISSUE TITLE
When using Rails 4.2.x, using "primary_key id, setting validates uniquness: ture" is failure judged

### ISSUE THREAD

**Issue by MatsumotoHiroko** [composite-primary-keys/composite_primary_keys#367]
I want to edit "id" and using rails validate is uniquness.
But this validate is true when I inputed not uniq "id".

---

My environment
Rails (4.2.6)
activerecord (4.2.6)
composite_primary_keys (8.1.4)

---

My code

model

```
class Item < ActiveRecord::Base
  validates :id, uniqueness: true,  numericality: true, presence: true, on: :update
  validates :id, uniqueness: true, numericality: true, allow_nil: true, allow_blank: true, on: :create
end
```

```
$rails console
> Item.all
id auto increment primary key
id | name
1  | item1
2  | item2

>item = Item.new(id: 1, name: "item3")
>item.save!
SELECT  1 AS one FROM `items` WHERE (`items`.`id` = BINARY 1 AND `items`.`id` != 1) LIMIT 1
=> true
```

---

I read code of this project.
(tag v8.1.4)
https://github.com/composite-primary-keys/composite_primary_keys/blob/v8.1.4/lib/composite_primary_keys/validations/uniqueness.rb

in this case, line 14,
`Array(finder_class.primary_key).zip(Array(record.send(:id))`
=>
`Array("id").zip(Array(1))`
created "`items`.`id` != 1" query.

How resolve does it?

Thanks.

**Comment by cfis** [comment]
Hmm, I can't duplicate this on master.  I added  a test in rc8fe747.

Can you provide a test to duplicate using CPK's test data?

**Comment by cfis** [comment]
Going to close since haven't heard back.
