### ISSUE TITLE
Please use `deep clone' in each `clone' method 

### ISSUE THREAD

**Issue by NaixSpirit** [composite-primary-keys/composite_primary_keys#371]
there is a [bug](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/relation/query_methods.rb#L28-L40) in the mater branch and ar_4.X.X branch

like this:

```ruby
  def order(*args)
    args.map! do |arg|
      if arg.is_a?(Arel::Nodes::Ordering) && arg.expr.name.is_a?(Array)
        arg = arg.expr.name.map do |key|
          cloned_node = arg.clone
          cloned_node.expr.name = key
          cloned_node
        end
      end
      arg
    end if composite?
    super(*args)
  end
```

the `arg.clone` is not deep clone, 
when first set `cloned_node.expr.name = key`,  also change the origin `arg.expr.name`, 
so the next set `cloned_node.expr.name = key`, it is change the origin `arg.expr.name`, it is changed the same thing!

a test like this:

```ruby
# the primary_keys is [:room_id, :product_uid]

  def order(*args)
    p args.flatten.map { |arg| arg.expr.name }  # => [["room_id", "product_uid"]]

    args.map! do |arg|
      if arg.is_a?(Arel::Nodes::Ordering) && arg.expr.name.is_a?(Array)
        arg = arg.expr.name.map do |key|
          cloned_node = arg.clone

          p cloned_node.expr.object_id    # => it is 70258564737800, not changed

          cloned_node.expr.name = key
          cloned_node
        end
      end
      arg
    end if composite?

    p args.flatten.map { |arg| arg.expr.name }   # => ["product_uid", "product_uid"]

    super(*args)
  end
```

we lost the primary_key `room_id`, because we set twice `cloned_node.expr.name`, but the `cloned_node.expr` is the same object, It depends on the last loop

we must deep clone the object to fix it

```ruby
  def order(*args)
    args.map! do |arg|
      if arg.is_a?(Arel::Nodes::Ordering) && arg.expr.name.is_a?(Array)
        arg = arg.expr.name.map do |key|
          cloned_node = arg.clone
          cloned_node.expr = arg.expr.clone  # also clone the expr object
          cloned_node.expr.name = key
          cloned_node
        end
      end
      arg
    end if composite?
    super(*args)
  end
```

**Comment by cfis** [comment]
Hmm, at least on the master branch that method is never used in the test suite. If I delete the method no tests fail.

**Comment by cfis** [comment]
Ah, I see, its called when using ActiveRecord#first or #last.  Removing the method seems to work fine...so its now gone defaulting to ActiveRecord's default behavior.  c5ee34aafe2deeee6e10accc9c3bd58feba516f8

**Comment by NaixSpirit** [comment]
yes, I called it when using ActiveRecord#first, removing the method could fix it, thanks
