### ISSUE TITLE
Not works with STI and non-default inheritance key

### ISSUE THREAD

**Issue by romkaspb** [composite-primary-keys/composite_primary_keys#376]
Hi.
Using STI in my project
```ruby
class Lesson < ApplicationRecord
  self.inheritance_column = :media_type
end

class Lesson::Video < Lesson
end
class Lesson::Html < Lesson
end
```

In this case I got "NoMethodError: undefined method `to_sym' for nil:NilClass".

If I not redefining inheritance_column - everything works fine.

Thanks.

**Comment by romkaspb** [comment]
But now, I think it's not depends on inheritance_column. As I understood it's relating with STI at all

**Comment by cfis** [comment]
Can you create a test case using the data in the CPK fixtures?  Hard to do much without a traceback.

**Comment by vill** [comment]
I have the same issue. I fix this error so:

```
class Lesson < ApplicationRecord
  self.primary_keys       = :id, :media_type
  self.inheritance_column = :media_type
end
```

P.S. I think this is not the optimal solution.

**Comment by cfis** [comment]
Ok, so not sure if this is an issue or not.  If it still is, please reopen.
