### ISSUE TITLE
Polymorphic associations and collection_singular_ids assignment

### ISSUE THREAD

**Issue by joshreeves** [composite-primary-keys/composite_primary_keys#379]
This is occurring with composite_primary_keys 9.0.6 and activerecord 5.0.0.1

I have a basic polymorphic `has_many :through` association. When attempting to use `collection_singular_ids` to assign multiple of the polymorphic associations, it fails when using the composite_primary_keys gem, even when the tables involved are using basic single-field `id` fields as their primary keys.

```
class Collection < ApplicationRecord
  has_many :collects
end

class Collect < ApplicationRecord
  belongs_to :collection
  belongs_to :collectible, polymorphic: true
end

class Item < ApplicationRecord
  has_many :collects, as: :collectible
  has_many :collections, through: :collects
end
```

Then when I do this:
```
c = Collection.find(1)
c.item_ids = [1,2,3,4,5]
```

I get the following error:

```
NameError: uninitialized constant Collect::Collectible
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-5.0.0.1/lib/active_record/inheritance.rb:152:in `compute_type'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-5.0.0.1/lib/active_record/reflection.rb:350:in `compute_class'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-5.0.0.1/lib/active_record/reflection.rb:346:in `klass'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/composite_primary_keys-9.0.4/lib/composite_primary_keys/associations/has_many_through_association.rb:23:in `delete_records'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:549:in `remove_records'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:542:in `block in delete_or_destroy'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-5.0.0.1/lib/active_record/associations/collection_association.rb:203:in `block in transaction'
	from /Users/joshr/.rvm/gems/ruby-2.3.2/gems/activerecord-

...etc...
```

If I remove the `composite_primary_keys` gem it works fine as expected.

**Comment by cfis** [comment]
Where is Collect::Collectible defined at?  That's not part of ActiveRecord or CPK.

**Comment by cfis** [comment]
Haven't heard back, closing.

**Comment by joshreeves** [comment]
@cfis `Collect::Collectible` seems to be what CPK *thinks* the class should be called when completing the `ids` assignment. It's not a real class, but it is CPK erroneously thinking that is what the class should be in the above scenario (which is a standard polymorphic relationship set up).

**Comment by cfis** [comment]
Oh  I see. Will reopen.

**Comment by ilyabyar** [comment]
Same thing for me. Not working with polymorphic associations.

**Comment by cfis** [comment]
Anyone want to update the existing polymorphic tests to include a failing one?

**Comment by cfis** [comment]
Ping?

**Comment by hugtrueme** [comment]
@cfis , Same thing for me. Not working with polymorphic associations.
