### ISSUE TITLE
PG::UndefinedColumn: ERROR:  column "role_id,permission_id" does not exist

### ISSUE THREAD

**Issue by Dorian** [composite-primary-keys/composite_primary_keys#384]
Just wanted to document it somewhere, I tried upgrading my gems and encountered this error highly probably related to `composite_primary_keys` and I didn't find how to fix it yet, so it's blocking my upgrades (will continue to investigate).

Examples include:

```
class RolePermission < Model
  self.primary_keys = :role_id, :permission_id
end

r = RolePermission.new # <RolePermissionJoin:... role_id: nil, permission_id: nil>
r.role_id = 1
r.permission_id = 1
r.save

# or

RolePermission.create(role_id: 1, permission_id: 1)

# SQL query: INSERT INTO "roles_permissions" ("role_id", "permission_id") VALUES ($1, $2) RETURNING "role_id,permission_id"

# or

RolePermission.find_or_create_by(role_id: 1, permission_id: 1)
```

Expected behavior:

```
INSERT INTO "roles_permissions" ("role_id", "permission_id") VALUES (1, 2) RETURNING "role_id", "permission_id"

# or

INSERT INTO "roles_permissions" ("role_id", "permission_id") VALUES (1, 2) RETURNING role_id, permission_id
```

So it's somewhere in the escaping of field names :)

Tried on `composite_primary_keys`: `9.0.4`, `9.0.6` and `master`.

**Comment by cfis** [comment]
Interesting that hasn't come up before...does look like a bug.  But it seems like there must be a test case for that in the CPK tests already.

**Comment by Dorian** [comment]
@cfis maybe it's an interaction with another gem, I try to investigate when I have time

**Comment by unDeveloper** [comment]
Nothing on this issue?

**Comment by cfis** [comment]
Haven't had a chance to look.  Would be good to add a test to the insert tests cases that ship CPK...

**Comment by unDeveloper** [comment]
Well, as far as i can see, the issue is the string. If i take the the query generated and split the columns name like `"role_id","permission_id"` the code succeed.  But i'm kinda new on gems, so maybe it will take a lot of time on fixing this. Thanks for your help @cfis, hope you can look at this soon.

**Comment by cfis** [comment]
I didn't mean fix it, just have a failing test.  That would make it easier for me to track down.

**Comment by Dorian** [comment]
My current guess is the interaction between lookup by and composite keys but couldn't make a failing test case

**Comment by cfis** [comment]
Notice the returning statement?  If the primary key is an array, then the return statement should not be added to the query. See:

https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L127

That code is actually in ActiveRecod.  So not sure what is unique about your setup, since the test_create.rb tests most definitely test this case and I've never seen it in any code that uses CPK.  

Next step here is for you to do a bit of debugging on your side.  The method suppress_composite_primary_key should return nil, but clearly is not. Why not?

**Comment by Dorian** [comment]
[rails 5.0](https://github.com/rails/rails/blob/5-0-stable/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L127):

```ruby
        def sql_for_insert(sql, pk, id_value, sequence_name, binds) # :nodoc:
          if pk.nil?
            # Extract the table from the insert sql. Yuck.
            table_ref = extract_table_ref_from_insert_sql(sql)
            pk = primary_key(table_ref) if table_ref
          end

          pk = suppress_composite_primary_key(pk)

          if pk && use_insert_returning?
            sql = "#{sql} RETURNING #{quote_column_name(pk)}"
          end

          super
        end
```

[rails 5.1](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L127) (same in [rails's master](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql/database_statements.rb#L127)):

```ruby
        def sql_for_insert(sql, pk, id_value, sequence_name, binds) # :nodoc:
          if pk.nil?
            # Extract the table from the insert sql. Yuck.
            table_ref = extract_table_ref_from_insert_sql(sql)
            pk = primary_key(table_ref) if table_ref
          end

          if pk = suppress_composite_primary_key(pk)
            sql = "#{sql} RETURNING #{quote_column_name(pk)}"
          end

          super
        end
        private :sql_for_insert
```

commit that changed it: https://github.com/rails/rails/commit/c48630b1ce1d7cf7e6a30f1eafd28ccedcc256ed

> Remove unnecessary `test_sql_for_insert_with_returning_disabled`
>
> Because `sql_for_insert` is only called in `use_insert_returning?` is
> true since #26002.

`#use_insert_returning?`, basically [`@use_insert_returning`](https://github.com/rails/rails/blob/00f1f95569a491c89bf78f08b78ebf0e6ff1d9d1/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L220) which is [a config for the postgres adapter](https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L61-L62).

Anyway, not sure what to do about it. I would rather fix it with ActiveRecord 5.1.

**Comment by cfis** [comment]
Well suppress_composite_primary_key(pk) should still return nil, so the RETURNING should not be included.

**Comment by mtarnovan** [comment]
Not sure if this is exclusively an ActiveRecord problem. I have the same issue after upgrading from 7df5fe (which I noticed now is tagged `9.0.4`) to `9.0.7` (with the same ActiveRecord version, namely `5.0.0.1`).

Should it help with debugging, I noticed that `ActiveRecord::ConnectionAdapters::PostgreSQL::DatabaseStatements#sql_for_insert` isn't even called when using 9.0.4

@Dorian what version of AR are you using?

**Comment by mtarnovan** [comment]
For me it's `9.0.5` that introduces this bug, probably due to the removal of the monkeypatched `postgresql_adapter` in 97f602cc461d60138e577d331815dd83ab316a39

**Comment by mtarnovan** [comment]
(Sorry for the multiple posts)

I think I found the problem, or at least parts of it. The monkeypatched `DatabaseStatements` that was removed in 97f602c calls `quote_column_names(pk)` (notice the plural) in `sql_for_insert`, while the monkeypatched AR file calls `quote_column_name(pk)` (singular):

```console
[22, 31] in /Users/mtarnovan/.rvm/gems/ruby-2.3.0@openapi2/bundler/gems/composite_primary_keys-e4e01a6df9fc/lib/composite_primary_keys/connection_adapters/postgresql_adapter.rb
   22:       alias :create :insert
   23: 
   24:       def sql_for_insert(sql, pk, id_value, sequence_name, binds)
   25:         debugger
   26: 
=> 27:         unless pk
   28:           # Extract the table from the insert sql. Yuck.
   29:           table_ref = extract_table_ref_from_insert_sql(sql)
   30:           pk = primary_key(table_ref) if table_ref
   31:         end
(byebug) quote_column_names(pk)
"\"cif\",\"year\""
(byebug) quote_column_name(pk)
"\"cif,year\""
(byebug) method(:quote_column_names).source_location
["/Users/mtarnovan/.rvm/gems/ruby-2.3.0@openapi2/bundler/gems/composite_primary_keys-e4e01a6df9fc/lib/composite_primary_keys/connection_adapters/abstract_adapter.rb", 4]
(byebug) method(:quote_column_name).source_location
["/Users/mtarnovan/.rvm/gems/ruby-2.3.0@openapi2/gems/activerecord-5.0.0.1/lib/active_record/connection_adapters/postgresql/quoting.rb", 44]
```

**Comment by Hamada92** [comment]
thanks @mtarnovan, downgrading to 9.0.4 worked for me, I'm on ActiveRecord 5.0.0.1

**Comment by Dorian** [comment]
BTW, we are on composite-primary-keys 9.0.6 and activerecord 5.0.3 and it's working (just a random data point :D)

**Comment by cfis** [comment]
Ok, updated the postgresql adapter to handle primary keys and returning statements on insert.
Thanks!
