### ISSUE TITLE
ActiveRecord::Base.record_timestamps not updating as set by Default in rails.

### ISSUE THREAD

**Issue by abr3222** [composite-primary-keys/composite_primary_keys#389]
Here is one Bug in this gem it effect the rails default way to Update these 2 Columns 
created_at and updated_at. 
Rails will automatically set those values when we create and update a model object.
if its Set as True.
```
pry(main)> ActiveRecord::Base.record_timestamps = true
=> true

pry(main)> User.create(:name => "Jeff")
=> #<User id: 11, name: "Name", created_at: nil, updated_at: nil>
```
But after including the gem it Overwrite the current way of storing the values we have to store it manually  now for each model every where in project even the value is True for timestamps.

```
pry(main)> User.create(:name => "Jeff" , :created_at=>Time.now )
=> #<User id: 12, name: "Name", created_at: "2017-03-02 17:27:00" , updated_at: nil>

```
Versions:
Rails: 4.1.1

Here is link for stackoverflow Issue related to this one.
http://stackoverflow.com/questions/42431532/activerecordbase-record-timestamps-not-working-as-supposed-to

**Comment by cfis** [comment]
Happy to take a patch.  But not supporting Rails 4.1.x anymore....

**Comment by cfis** [comment]
Haven't heard back, closing.
