### ISSUE TITLE
it's breaking with rails 5.1.0.rc1

### ISSUE THREAD

**Issue by pinak1180** [composite-primary-keys/composite_primary_keys#394]
it's not working at all with rails 5.1.0.rc1, I think it's due to https://github.com/rails/rails/commit/47b2ddd34da7dfabcda06d7fca39c1ca03ea87cc

**Comment by mensfeld** [comment]
:+1:  really need this one

**Comment by pinak1180** [comment]
@mensfeld  i did one small patch as you can see and it seems to work.

**Comment by mensfeld** [comment]
@pinak1180  yeah I know, however I use this gem in a... gem :D so I can't use non-released things.

**Comment by batmanbury** [comment]
Thanks, @pinak1180 I'll be using this until it's resolved in the meantime. 👍

**Comment by bryanrichardson** [comment]
Any idea when this might hit master along with a gemspec update to target AR 5.1?

**Comment by Dorian** [comment]
`activerecord-oracle_enhanced-adapter` is preventing upgrading to rails 5.1, there is also a hard-coded dependency in `lib/composite_primary_keys.rb`:

> `gem 'activerecord', '~>5.0.0.beta3'`

And then running the specs, I get a bunch of errors.

**Comment by cfis** [comment]
All, I applied this patch.  There are still 2 failures and 17 errors.  From experience, updating to new Rails versions can take 40 to 100 hours of work.  Maybe this time will be easier.

Anyway, master branch updated.  Patches welcome to fix the other issues.  I will get to these errors, but expect it to be in the June/July timeframe.
