### ISSUE TITLE
8.1.5 on Rails 4.2.8, association returns wrong entry

### ISSUE THREAD

**Issue by GavinScottQss** [composite-primary-keys/composite_primary_keys#396]
After upgrading to Rials 4.2 from 4.1, we are getting numerous issues that all seem to all stem from composite_primary_keys associations returning the wrong associated record. Besides various other failures, this is causing database corruption when saving a model with autosave: true, where something seems to set what it thinks are the key fields in other associated models back to their original values(?) and this also uses the wrong composite_primary_keys derived entry which results in a field getting changed (rather than changed to the identical value) thus dirtying the record and causing it to get posted back to the DB unexpectedly changing a record that should never be possible to change and in this case changing Employee A's Employee Number to that of Employee B, which is rather bad.

With these two models set up:

class EssAbsence < ActiveRecord::Base
  has_many :perpay,
    #-> { select(:di_no, :emp_no, :last_name) }, # fails when commented out, works when uncommented
    class_name: 'PerPay',
    primary_key: [:di_no, :emp_no],
    foreign_key: [:di_no, :emp_no]
end

class PerPay < ActiveRecord::Base
  self.table_name = 'per_pay'
end

and with trivial table field definitions like
  di_no: integer
  emp_no: integer
  last_name: character(32)

We see the flowing behavior:

e=EssAbsence.where('emp_no=1').first
e.perpay (returns the correct associated record)
e=EssAbsence.where('emp_no=2').first
e.perpay (returns the same record as above, not the correct one!)

If the select() qualifier is uncommented then it works, but otherwise we're getting the previously retrieved values back.

Works with Rails 4.1.15-16 and is broken on 4.2.7.1 / 4.2.8.

Steps to reproduce the composite_primary_keys has_many wrong data problem:

1) build and install ruby 2.3.3
2) gem install pg --no-document
3) gem install rails --no-document -v 4.2.8
4) gem install composite_primary_keys --no-document -v 8.1.5
5) rails new myapp
6) edit myapp/Gemfile to include just rails, pg, and composite_primary_keys gems
7) cd myapp
8) bundle install (to reflect Gemfile editing)
9) add the demo models to app/models
10) edit config/database.yml:
	"development" database entry pointing to the PostgreSQL database containing the ess_absences and per_pay tables
11) rails console:
	retrieve two rows with different foreign keys
	a=EssAbsence.where('emp_no=1').first
	b=EssAbsence.where('emp_no=2').first
	a.perpay # retrieves correct association object from per_pay table
	b.perpay # INCORRECTLY re-retrieves the per_pay object from the "a" object above
12) Uncomment the EssAbsence has_many proc select() list and re-perform the same queries which will now work properly.

**Comment by ttwo32** [comment]
Hi @GavinScottQss !! 
Please look at https://github.com/composite-primary-keys/composite_primary_keys/issues/385 !!
If this is a same to my above PR, i had solved it.:)

**Comment by GavinScottQss** [comment]
Thanks. A quick test suggests that your fix resolves the issue here.

It would be great if this could be pushed to a new release soon.

**Comment by ttwo32** [comment]
my plebsure.:)
Yep, i,m waiting to next release too.

**Comment by cfis** [comment]
I just made a new release.  Sorry for the delay..

**Comment by ttwo32** [comment]
@cfis Thank you for making a new release.😄

**Comment by GavinScottQss** [comment]
Yes,​ thanks everyone who worked on solving this issue and getting the new release out!



Gavin
