### ISSUE TITLE
Does it support scopes to search by primary keys?

### ISSUE THREAD

**Issue by tommyalvarez** [composite-primary-keys/composite_primary_keys#400]
Hi,

I have a multi column primary key model. I need to do something like:

`records_to_filter_out = [[pk_column1_record_1,pk_column2_record_2], [pk_column1_record_2,pk_column2_record_2], pk_column1_record_3,pk_column2_record_3]]`

`scope :except, -> (filter_records) {where.not(compound_primary_key: filter_records}`

Is it possible? Basically, given a N amount of compound primary keys in an array, i need to perform a query to get all records except some of them, which are pointed out by the array.

**Comment by cfis** [comment]
Hmm, have you tried it?  You can certainly select by keys.  Wouldnt' be too hard to write a method to do the inverse.
