### ISSUE TITLE
Breaks primary_key detection with SQLServer Adapter

### ISSUE THREAD

**Issue by neongrau** [composite-primary-keys/composite_primary_keys#401]
Any call of `.find(123)` with a single id fails to detect the primary key used for default ordering .

```
Stuff.find(7)
ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near 'OFFSET'.: EXEC sp_executesql N'SELECT  [stuffs].* FROM [stuffs] WHERE [stuffs].[id] = @0 OFFSET 0 ROWS FETCH NEXT @1 ROWS ONLY', N'@0 int, @1 int', @0 = 7, @1 = 1
```

`Stuff.first` strangely does work:

```
irb(main):003:0> Stuff.first
  Stuff Load (0.0ms)  EXEC sp_executesql N'SELECT  [stuffs].* FROM [stuffs]  ORDER BY id OFFSET 0 ROWS FETCH NEXT @0 ROWS ONLY', N'@0 int', @0 = 1  [["LIMIT", 1]]
```

There `id` was detected as primary key and used for the `ORDER BY`which is required for the `OFFSET ... ROWS FETCH NEXT ... ONLY` syntax.

**Comment by cfis** [comment]
Hmm, not very familiar with sql server.  Want to submit a patch?

**Comment by cfis** [comment]
Going to close, since there was no followup.
