### ISSUE TITLE
Insertion doesn't work when composite primary_key is defined in the rails model

### ISSUE THREAD

**Issue by sumitdey035** [composite-primary-keys/composite_primary_keys#405]
### Steps to reproduce
I added a composite key in the model Link
**Link Model**
```
class Link < ActiveRecord::Base
  self.primary_keys = :link_id, :map_id
end
```
**Link migration**
```
class CreateLinks < ActiveRecord::Migration
  def change
    create_table :links do |t|
      t.integer :link_id
      t.integer :map_id
      t.string :name
    end
  end
end
```
**Trying to create links from console**

> [1] pry(main)> Link.create(link_id: 12345, map_id: 100, name: "kj")
>  
>   SQL (63.0ms)  INSERT INTO "LINKS" ("LINK_ID", "MAP_ID", "NAME", "link_id,map_id") VALUES (:a1, :a2, :a3, :a4)  [["link_id", 12345], ["map_id", 100], ["name", "kj"], [nil, 1]]
> ActiveRecord::StatementInvalid: NoMethodError: undefined method `returning_id?' for nil:NilClass: INSERT INTO "LINKS" ("LINK_ID", "MAP_ID", "NAME", "link_id,map_id") VALUES (:a1, :a2, :a3, :a4)

### System configuration
**Rails version**: 4.2.8

**Composite Primary Keys version**: 8.1.6

**Ruby version**: JRuby 9.1.5.0

**Oracle Database version**: 12c(1st release)

**activerecord-oracle_enhanced-adapter**:  1.6.9 (this gem is for oracle adapter)

**Comment by cfis** [comment]
Yeah, you'll need to do that via SQL.  Or alternatively patch ActiveRecord to support it.
