### ISSUE TITLE
composite_primary_keys is not compatible with rails 4.2.6

### ISSUE THREAD

**Issue by yasirrose** [composite-primary-keys/composite_primary_keys#409]
Can you please create a pull request for me to use composite primary keys for rails 4.2.6. Or guide me that which version should i use?

**Comment by ilyabyar** [comment]
:+1: Could you please tell me if I can use it with Rails 4.2.8, which version of gem or Rails should I use?
I am using it with `papertrail`, `activerecord-import` and have some strange issues with some queries.

**Comment by cfis** [comment]
Happy to take a pull request for the ar_4.2.x branch...but I won't be updating it since its no longer supported by the Rails team.
