### ISSUE TITLE
Does CPK work for db:structure:dump with activerecord-oracle_enhanced-adapter?

### ISSUE THREAD

**Issue by dgarwood** [composite-primary-keys/composite_primary_keys#411]
I'm working on getting an old oracle database that was built with composite keys working with rails.  Part of that effort requires that pl/sql code is included in the database dump, which requires `config.active_record.schema_format = :sql` set.

Currently, with CPK and the oracle_enhanced-adapter installed, composite foreign keys are not dumped properly, creating a FK reference for each column in the composite foreign key rather than a single entry.  This was the behavior of the adaptor before adding CPK to the Gemfile.

Does CPK work with `:sql` formatting?  If so, is there a config setting that I might have missed to ensure this works with activerecord-oracle_enhanced-adaptor?

rails: 5.0.5
cpk: 9.0.7
oracle_enhanced: 1.7.11

**Comment by cfis** [comment]
I wouldn't think that CPK would affect :sql formatting....Perhaps to make it work the ActiveRecord code would need to be updated?  Not sure, but happy to review a patch.
