### ISSUE TITLE
find_or_initialize_by do not work

### ISSUE THREAD

**Issue by kurtov** [composite-primary-keys/composite_primary_keys#414]
let's look at test model `PkCalledId` (DB: postgres, gem: `git checkout v9.0.7` or `git checkout master`)

1. If I write
``` ruby
PkCalledId.find_or_initialize_by(id: [2, 1])
```
I get incorrect query
``` sql
SELECT  "pk_called_ids".* FROM "pk_called_ids" WHERE "pk_called_ids"."id" IN (2, 1) LIMIT $1 [["LIMIT", 1]]
```
2. If I write
``` ruby
PkCalledId.find_or_initialize_by(id: 2, reference_code: 1)
```

and record exists I get correct query
``` sql
SELECT  "pk_called_ids".* FROM "pk_called_ids" WHERE "pk_called_ids"."id" = $1 AND "pk_called_ids"."reference_code" = $2 LIMIT $3  [["id", 2], ["reference_code", 1], ["LIMIT", 1]]
```
but if record does not exist I get exception `ArgumentError: Unsupported type: 2` because it expects Array, not Fixnum.

Therefore, I use this code
``` ruby
find_by(id: id, reference_code: reference_code) || new(id: [id, reference_code])
```

**Comment by cfis** [comment]
Yes, I think that is a reasonable workaround.  find_by_initailize calls find_by which call where.  So CPK would have to override where to check for an attribute called id.  Don't think its worth doing that.
