### ISSUE TITLE
use `subquery_for` in composite_primary_keys rather than using that one in active_record as default 

### ISSUE THREAD

**Issue by denglitong** [composite-primary-keys/composite_primary_keys#423]
my activerecord version is 4.2.8, so i use composite_primary_keys 8.1.6, but it occur that when one of my model which `has_many` :table_name, :composite_table and use .delete_all method, at last it use the function subquery_for in composite_primary_keys rather than which in active_record default!

Now, my question is, how can i specify use composite_primary_keys in smallest auth in my code, for example just in that one modle file, rather than in my whole rails app.

Any responce is high preciated! thank you very much!

**Comment by cfis** [comment]
The overriden method by CPK should be safe to always use.  Are you encountering a bug with it? If so, patches welcome.  Note that CPK for Rails 4.x is no longer supported though.

**Comment by denglitong** [comment]
Thanks any way!
