### ISSUE TITLE
superclass mismatch for class SQLServer (TypeError) when used with activerecord-sqlserver-adapter

### ISSUE THREAD

**Issue by hallabassee** [composite-primary-keys/composite_primary_keys#425]
Using composite_primary_keys (v10.0.2) with activerecord-sqlserver-adapter (v5.1.5), I get a superclass mismatch for class SQLServer.  I was able to resolve it by updating SQLServer to inherit Arel::Visitors::ToSql to match activerecord-sqlserver-adapter.

**Comment by cfis** [comment]
Actually that is not what you want to do.  Instead, you want to require the activerecord-sqlserver-adapter/lib/arel/visitors/sqlserver file *before* the CPK override loads.  The gem doesn't do that because most people aren't using sql server and I'm not sure of a way to auto detect that.
