### ISSUE TITLE
Composite keys seems to prevent after_commit callback on touch

### ISSUE THREAD

**Issue by jharbert** [composite-primary-keys/composite_primary_keys#427]
I have a model that calls a method via `after_commit, on: :update` callback:

```
object.rb:

after_commit :some_method, on: :update
```

I noticed with this gem in place, a test that called `object.touch` did not call `some_method`.  With Rails 5, `after_commit` is called on `touch` (https://github.com/rails/rails/pull/18458)

I wish I could give more info.  I traced the issue seemingly to `/composite_primary_keys/persistence.rb`.  I did not end up needing composite keys in the app so I removed the gem and the issue was resolved.

**Comment by cfis** [comment]
Thanks for the heads up.
