### ISSUE TITLE
code is added to every class whether or not there is a composite index or just a simple id key.

### ISSUE THREAD

**Issue by itcentralstation** [composite-primary-keys/composite_primary_keys#430]
In the current design, code is added to every AR class whether or not there is a need for the code, that is, whether or not the table has a composite index or just a simple id key.

This means that EVERY .find(), .last(), .first(), .update() in our code base will using the functions provided by this gem.

I would feel a lot more comfortable if the functionality was added with either an **include** or by deriving the class from a middle class like `CompositeIDRecrod < ActiveRecord::Base`. That way, only the specific tables are relying on this gem.

Is there anyway to do this?

**Comment by cfis** [comment]
Its actually a bit of both.  In the case of find, I don't think you are correct.  See relation.rb:

    def add_cpk_support
      extend CompositePrimaryKeys::CompositeRelation
    end

Anyway, happy to accept patches that separate things out more as long as the test suite still passes. 

Charlie

**Comment by cfis** [comment]
Happy to take patches if you'd like to provide some.
