### ISSUE TITLE
in find_one: TypeError: wrong argument type Integer (must respond to :each)

### ISSUE THREAD

**Issue by coconup** [composite-primary-keys/composite_primary_keys#438]
https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_5.1.x/lib/composite_primary_keys/relation/finder_methods.rb#L172

This line in the find_one method is raising an exception, as the invoked method expects the `id` argument to be an array.

A simple fix would be to wrap ID into an array, maybe after a `kind_of?` check.

**Comment by daschi** [comment]
This is also an issue when trying to use active record to `update` a record's attributes.

```
Record.find(:id).update(attr: 'attr')
TypeError (wrong argument type Integer (must respond to :each))
```

**Comment by cfis** [comment]
Hmm, I'm going to call this as designed.

**Comment by coconup** [comment]
@cfis thanks for looking into this. I don't think this is by design though, the `cpk_id_predicate` accepts `values` as its last argument, and it clearly expects this to be an array. 

The `find_one` method, on the other hand, is passing `id` (singular) as third argument. It's not just a matter of naming, it's clear by looking at `find_one` that `id` is not going to be an array (see e.g. [here](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/relation/finder_methods.rb#L89)), thus `cpk_id_predicate` ([here](https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_5.1.x/lib/composite_primary_keys/composite_predicates.rb#L34)) is always going to raise an exception when called from [this line](https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_5.1.x/lib/composite_primary_keys/relation/finder_methods.rb#L172)

**Comment by Plotist** [comment]
@cfis I agree with @coconup .
I'm having a same issue here

**Comment by Kasvit** [comment]
Hello @coconup  I have problems with this issue too:

Record.primary_key -> ["field1", "field2"]
Record.find(1) -> TypeError (wrong argument type Integer (must respond to :each))
Record.find([1,2])  -> worked

Gemfile.lock
composite_primary_keys (12.0.1)
      activerecord (~> 6.0.0)

**Comment by cfis** [comment]
Still think this is as designed. CPK used to try and be smarter about this many versions ago, but the code got really confusing with all the possibilities that it was simplified.
