### ISSUE TITLE
delete_all ActiveRecord instance method does not work properly anymore

### ISSUE THREAD

**Issue by Victorcorcos** [composite-primary-keys/composite_primary_keys#444]
On the latest version of this gem, the `delete_all` instance method is deleting everything on the model even if some restrictions are applied before the deletion. This bug particularly happens when a model is joined with another one before the deletion.

For example, assume that a random model (`Asset`) `belongs_to` other random model (`Project`).
The `Asset` model has `5` records.

Let see what happens with the following commands...

```
Asset.joins(:project)
```
or
```
Asset.joins(:project).count
```

After running these commands we can see that we have 5 records of `Assets` associated with `Project`.
Now, let's run other commands:

```
Asset.joins(:project).where(id: nil)
```

We can see that none of the records has `id: nil`
**However**, when we execute the following command:

```
Asset.joins(:project).where(id: nil).delete_all
```

All records related to the the `Asset` model are deleted somehow! 😢 

```
Asset.count
```
Returns `0` now.

This is a serious bug of the composite_primary_keys gem and it is a problem related with the `subquery_for(key, select)` method that this gem overwrites from `ActiveRecord`. This problem is happening after this commit: https://github.com/kaefer-cit/composite_primary_keys/commit/d989a51def2519f89a0b4483120a340670bb783b

Before this commit, **it was not even possible to execute the `delete_all` after joining two tables**.

If someone can fix this, I'll be grateful.

Peace

**Comment by Victorcorcos** [comment]
![screen shot 2018-04-17 at 15 47 17](https://user-images.githubusercontent.com/7637806/38890955-502525b2-4259-11e8-9e66-1b97bd31adab.png)

**Comment by Victorcorcos** [comment]
I just removed the `composite_primary_keys` gem from my Gemfile and the `delete_all` command is working properly when a model is joined with another one before the deletion.

![screen shot 2018-04-17 at 18 03 45](https://user-images.githubusercontent.com/7637806/38896662-b92634f6-4269-11e8-8b59-fcf9e5670ed9.png)

**Comment by Victorcorcos** [comment]
On the below picture you guys can check the different SQL queries and where the bug precisely takes place.

## With the gem (serious bug on `delete_all`)
![screen shot 2018-04-17 at 18 08 19](https://user-images.githubusercontent.com/7637806/38898494-8c650ee0-426b-11e8-91c3-f3165f78fc3f.png)

## Without the gem (everything is normal on `delete_all`)
![screen shot 2018-04-17 at 18 08 10](https://user-images.githubusercontent.com/7637806/38898498-916dfabe-426b-11e8-844f-a759e8e0fa71.png)

**Comment by cfis** [comment]
Ah that's not good.  I reverted that change, definitely don't want to be deleting too much.
