### ISSUE TITLE
active_record/locking/optimistic.rb doesn't have 'increment_lock' method

### ISSUE THREAD

**Issue by altblanc** [composite-primary-keys/composite_primary_keys#447]
ActiveRecord 5.2 doesn't have increment_lock method, so maybe an error occurred in optimistic.rb.

```(ruby)
module ActiveRecord
  module Locking
    module Optimistic
      def _update_record(attribute_names = self.attribute_names)
        return super unless locking_enabled?
        return 0 if attribute_names.empty?

        begin
          lock_col = self.class.locking_column
          previous_lock_value = read_attribute_before_type_cast(lock_col)
          increment_lock
          attribute_names.push(lock_col)
          relation = self.class.unscoped

  ...
```

**Comment by mshiltonj** [comment]
Temporary workaround monkeypatch:

class ActiveRecord::Base
  def increment_lock
    self[self.class.locking_column] += 1
  end
end

**Comment by altblanc** [comment]
thanks for your comment. I use it!

**Comment by rlue** [comment]
This is still a problem on older versions of `composite_primary_keys`: the `ar_5.1.x` branch still references the `#increment_lock` method, which is [not present in AR 5.1 stable](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/locking/optimistic.rb).

I'm working on an application that uses `composite_primary_keys` v10.0.5, and can't upgrade until we upgrade to Rails 5.2 (which is happening, but not right now). Any chance we can have this issue reopened until we get a backported fix?

**Comment by cfis** [comment]
Sure.  Someone want to provide a patch?

**Comment by rlue** [comment]
So I've looked into this issue, and here's what I found:

* `#increment_lock` was removed from `ActiveRecord::Persistence` in [`aaee10e`](https://github.com/rails/rails/commit/aaee10e6e4fdfbc8bb7dc6169ed9deea3638c5a8#diff-e8099d3205c1cc5136a5441174a6078b).

  Now, the lock counter is incremented in `ActiveRecord::Locking::Optimistic#_update_row` (a private method), which is designed to override `ActiveRecord::Persistence#_update_row`.

* This version of `#_update_row` was [introduced in Rails 5.1.6](https://github.com/rails/rails/blob/v5.1.6/activerecord/lib/active_record/locking/optimistic.rb) (_i.e.,_ it was [absent in Rails 5.1.5](https://github.com/rails/rails/blob/v5.1.5/activerecord/lib/active_record/locking/optimistic.rb).

So my understanding is that in order for CPK 10.x to support all versions of Rails 5.1.x, it can rely on neither `#increment_lock` nor `#_update_row`. Instead, it should have its own verbatim copy of the lock-counter-increment logic.

Is this the right approach? I'm still rather new to maintaining/backporting changes to old software, so please forgive me if I've gotten something wrong about how this works.

**Comment by cfis** [comment]
Works for me, applied the commit.
