### ISSUE TITLE
Use `ActiveSupport.on_load` to hook into ActiveRecord 

### ISSUE THREAD

**Issue by f-mer** [composite-primary-keys/composite_primary_keys#454]
Following up on rails/rails#23589 I guess overrides should take place after active-record has loaded.
So [all `requires`](https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys.rb#L33-L116) should be wrapped inside an `ActiveSupport.on_load(:active_record)` block.

Would happily supply a PR if my concerns are valid.

**Comment by cfis** [comment]
The CPK gem is dependent on ActiveRecord, so bundler will ensure ActiveRecord is first loaded. So this should not be an issue.
