### ISSUE TITLE
Error using has_one with inverse_of and array primary key

### ISSUE THREAD

**Issue by natematykiewicz** [composite-primary-keys/composite_primary_keys#455]
I have a has_one association that uses inverse_of, along with array primary and foreign keys.

```ruby
has_one :dealership,
  primary_key: [:customer_id, :id],
  foreign_key: [:customer_id, :company_id],
  inverse_of: :company
```

I get `TypeError: [:customer_id, :id] is not a symbol nor a string`.

If I remove the inverse_of, the association seems to work, but then I don't have usable inverses which is problematic.

I experience this issue in v10.0.4 with Rails 5.1.6 and v11.0.1 with Rails 5.2.0. Interestingly, v8.1.6 with Rails 4.2.9 works fine.

For clarification, I have plenty of `has_many` and `belongs_to` associations that work great. The `has_one` code is missing a monkey patch that this gem usually adds.

**Comment by natematykiewicz** [comment]
Any thoughts on this?

**Comment by kingdonb** [comment]
I think you want to say "primary_keys" not "primary_key"

https://github.com/composite-primary-keys/composite_primary_keys#the-basics

Everyone makes this mistake at least once!

**Comment by kingdonb** [comment]
We were working on similar issues in our Oracle database, there's a reason why best-practice advice seems to push you quickly toward "if you're thinking of using composite primary keys in Rails, first.. don't"

But I think we worked it out.  Keep your eye on the activerecord query logs, if you have them going to a log file, maybe better that you redirect them to stdout.  (I think this might even be the default now in Rails 5.)

What wound up solving the problem for us is, on our has-many<->belongs-to, you need to define the inverse_of and you need to define foreign_key anywhere that the default rule would infer an incorrect foreign key.

I think I know how it should look, after a half day of debugging, but this is why I say... you need to provide the actual definitions of each class and the relationships that you expect to be on them here, or it will be very difficult for anyone to help you debug the issue.  While it's fresh in my mind, I don't think it will be too hard for me to point at the spot that is missing the foreign_key, or where it's defined incorrectly.

If you have a has_many or has_one with belongs_to, you need to define the foreign_key on the inverse_of relationship.

**Comment by kingdonb** [comment]
The best trick I found to help with debugging is to read the actual queries that Rails is generating for you, and figure out where it has made the mistake.  Short of reading your code, I'm not sure there's any more help to offer!  It's very tricky to get these relations exactly right, but rewarding.

**Comment by natematykiewicz** [comment]
I understand all of the reasons to not use composite primary keys in Rails. This is a multi-tenanted database that’s like 15 years old.

I’ve just updated the original post, but my problem is no fault of my own. This gem has a bug specifically with `has_one` associations. I have plenty of `has_many` and `belongs_to` associations that work fine. You mention specifying `inverse_of’, but that’s literally my problem. When specifying an inverse, the `has_one` method does not expect an array of primary keys. The gem is missing a monkey patch that it added to all of the other associations. 

The association does not error when an inverse is not provided, but it also does not have a correct inverse assigned. My current workaround is to use a `has_many` and take the first record.

Can you try making a `has_one` association that uses ‘inverse_of`? This feature worked in Rails 4.X, but was broken when they released the Rails 5.X versions of the gem.

I can’t use the class method `primary_keys=` because that seems buggy too. It’s not assigning the ids back in from the save like active record typically does. ActiveRecord without an id is no good.

**Comment by kingdonb** [comment]
> I understand all of the reasons to not use composite primary keys in Rails. This is a multi-tenanted database that’s like 15 years old.

Me too, that's why I'm here, going against the advice like you...

I might even have a has_one in my data tables already.  I will try it out this weekend and post back!

**Comment by natematykiewicz** [comment]
As a workaround for this issue, my coworker added this Monkey Patch to our code:

```ruby
# Fix: https://github.com/composite-primary-keys/composite_primary_keys/issues/455

# rubocop:disable all
module ActiveRecord
  module AutosaveAssociation

    def save_has_one_association(reflection)
      association = association_instance_get(reflection.name)
      record      = association && association.load_target

      if record && !record.destroyed?
        autosave = reflection.options[:autosave]

        if autosave && record.marked_for_destruction?
          record.destroy
        elsif autosave != false
          key = if (__key = reflection.options[:primary_key])
            __key.is_a?(Array) ?  __key.map {|a| send(a) } : send(reflection.options[:primary_key])
          else
            id
          end

          if (autosave && record.changed_for_autosave?) || new_record? || record_changed?(reflection, record, key)
            unless reflection.through_reflection
              record[reflection.foreign_key] = key
              if inverse_reflection = reflection.inverse_of
                record.association(inverse_reflection.name).loaded!
              end
            end

            saved = record.save(validate: !autosave)
            raise ActiveRecord::Rollback if !saved && autosave
            saved
          end
        end
      end
    end

  end
end
```

From what he said, it's specifically this line that needed changing:
`__key.is_a?(Array) ?  __key.map {|a| send(a) } : send(reflection.options[:primary_key])`

I believe he said that it used to just simply `send(reflection.options[:primary_key])`, and so he added the map if it's an array.
