### ISSUE TITLE
11.1 Broken on #find_each in Rails 5.2.2

### ISSUE THREAD

**Issue by codeodor** [composite-primary-keys/composite_primary_keys#470]
When using `#find_each` on an model through an association, I get this error:

```
undefined method `act_on_order_or_limit_ignored' for #<MyModel::ActiveRecord_AssociationRelation:...>)
```

I'm not sure if it's only through an association or more general, but I don't have time to investigate at the moment, so I just wanted to report.

**Comment by codeodor** [comment]
This is on mysql BTW

**Comment by codeodor** [comment]
```ruby
def test_find_each_does_not_throw_error
    tariffs = Tariff.includes(:product_tariffs)
    worked = false
    tariffs.first.product_tariffs.find_each do |pt|
      worked = true
    end
    assert worked
  end
```

That works. So, maybe it's deeper. :(

I'll try to look into it some more later.

**Comment by codeodor** [comment]
Ah, here we go. It needs to be ordered. So, this test duplicates the issue:

```ruby
def test_find_each_does_not_throw_error
    tariffs = Tariff.includes(:product_tariffs)
    worked = false
    tariffs.first.product_tariffs.order(:tariff_id).find_each do |pt|
      worked = true
    end
    assert worked
  end
```

**Comment by codeodor** [comment]
(It fails on postgresql too)

Ok, really gotta run now. Sorry for the barage of comments.

**Comment by cfis** [comment]
Looks good, can you commit this (I added you as a collaborator)?
