### ISSUE TITLE
undefined method `association' for nil:NilClass

### ISSUE THREAD

**Issue by codeodor** [composite-primary-keys/composite_primary_keys#475]
```ruby
Model.where(conditions).order(columns).includes(:associated_model)
``` 

fails with the error message 

```
undefined method `association' for nil:NilClass
```

I can get around it by changing it to:

```ruby
Model.where(conditions).order(columns).references(:associated_model).includes(:associated_model)
```

This is on Rails 5.2.

**Comment by cfis** [comment]
Hmm...I take it that doesn't happen for non CPK models?

**Comment by codeodor** [comment]
Correct. I didn't have time to look into it any more than that, so I wanted to leave my workaround for others who might come into the same issue. 

I wish I made note of where in my app I was seeing that, so I could tell if it was still an issue without writing up a full test case. 

But I will hopefully get around to it at some point!

**Comment by cfis** [comment]
Took a look but I couldn't reproduce - see test case I added.
