### ISSUE TITLE
Awkward behaviour when using `:id` in the primary key

### ISSUE THREAD

**Issue by mberlanda** [composite-primary-keys/composite_primary_keys#477]
I am trying to add this gem to an existing project and several behaviour looks broken when the primary_key is set to `[:id, :something_else]`:

- some_else.my_models.create! => it won't assign the `:id` auto increment
-  my_model.create! => cannot propagate correctly some foreign keys
- when passing an ActiveRecord relation the where clause does not resolve correctly

you can refer to https://github.com/composite-primary-keys/composite_primary_keys/pull/476 for a full example.

Would be enough to add a new column and use it instead of `:id` to fix the issue?

**Comment by mberlanda** [comment]
Renaming the `:id` column to `:something_id` will fix the most of the problems but it is still not possible to do:

`my_model.something_else.create!`:
https://github.com/composite-primary-keys/composite_primary_keys/commit/6c2d19b8f6b8287c1d7f9852986003c5ebce8ff0

**Comment by cfis** [comment]
Yes, this has come up before. Take a look at #319.

**Comment by mberlanda** [comment]
Hey @cfis , thank you for your reply! Unfortunately the fix #370 seems to be not working at 100%. I put some sample tests in the draft pr #476

**Comment by codeodor** [comment]
@mberlanda I'm curious: if you change the test so that the ID is not autoincrement, do the other two problems go away, or do they remain?

And if so, is there any drawback to not defining a composite key on this model in Rails, since it's autoincrement ID is already unique?

**Comment by mberlanda** [comment]
@codeodor I have tried to rename `id` with `pk_user_id` in this commit: https://github.com/composite-primary-keys/composite_primary_keys/commit/6c2d19b8f6b8287c1d7f9852986003c5ebce8ff0

This fix the way the SQL is rendered but I still cannot create a related resource starting from the CPK model:

`pk_user.pk_posts.create!(title: 'title1')` still raises.

I also noticed that sometimes `.id` seems to be used by AR as an alias of `.attributes[:id]` and other times as `.primary_key` 😕

**Comment by cfis** [comment]
See primary_key.rb - its always the primary key.

`      # Returns the primary key value.
      def id
        sync_with_transaction_state
        primary_key = self.class.primary_key
        _read_attribute(primary_key) if primary_key
      end
`

**Comment by mberlanda** [comment]
hey @cfis 

thank you very much for getting back to me!
I added one more commit to the draft PR created to add some testing for the issue I am facing (#476):

https://github.com/composite-primary-keys/composite_primary_keys/pull/476/commits/15c5a6268b253c605639b57666f1c334be2833a2

You can see that `.pluck` will return the attribute `id` whilst `.map` is returning as expected the CPK.

Those tests are passing in mysql running with `bundle exec rake mysql:test TEST=test/test_pk_user_id.rb`

**Comment by cfis** [comment]
Based on changes in b0413f5 I'm going to close this. Note that calling model.id is still going to give you back an array, there really is no way around that. But model.attributes['id'] will give you back the right value. Create seems to work, and there are some fixes with associations. So hopefully this is workable now.
