### ISSUE TITLE
v8.1.6: bug in loading associations for a new record

### ISSUE THREAD

**Issue by ainar-g** [composite-primary-keys/composite_primary_keys#478]
```rb
# CREATE TABLE as (id INT PRIMARY KEY, key TEXT);
# CREATE TABLE bs (id INT PRIMARY KEY, key TEXT);
class A < ActiveRecord::Base
  has_many :bs, foreign_key: :key, primary_key: :key
end
class B < ActiveRecord::Base
end

B.create!(id: 1, key: "foo")
a = A.new(key: "foo")
puts(a.bs.count)
```

Without the gem, it prints `1`, as it should. With the gem, it's `0`. The problem is an apparent misprint in `lib/composite_primary_keys/associations/has_many_association.rb`:

```rb
# CPK
# owner.attribute_present?(reflection.association_primary_key)
Array(reflection.klass.primary_key).all? {|key| owner.attribute_present?(key)}
```

It should be `Array(reflection.association_primary_key)`.

**Comment by cfis** [comment]
Yup, sure looks like it.  I don't maintain the 8.x branch anymore, but I'm can merge a pull request if you send one along.
