### ISSUE TITLE
11.2 breaks find_or_create_by!

### ISSUE THREAD

**Issue by ToniTornado** [composite-primary-keys/composite_primary_keys#479]
This worked until 11.1.0 but now gives an error in 11.2.0:

```
class MyModel < ActiveRecord::Base
  self.table_name = :legacytable
  self.primary_keys = :username, :groupname
end

MyModel.find_or_create_by!(
  UserName: 'no yet in database',
  GroupName: '1',
  priority: 0
)
```

`ArgumentError (Unsupported type: 0)`

I couldn't figure out where it comes from but I fixed the gem version to 11.1.0.

`gem 'composite_primary_keys', '=11.1.0'`

**Comment by cfis** [comment]
Hmm, I can't reproduce (see test).  Would need to get a traceback to look more.
