### ISSUE TITLE
select distinct count bug

### ISSUE THREAD

**Issue by lpy-neo** [composite-primary-keys/composite_primary_keys#481]
Hi, I found a bug:
  rails statement: 
    relation.select(:id,:user_id).uniq.count
  will produce mysql query statement:
    SELECT COUNT(DISTINCT count_column) FROM (SELECT DISTINCT ...

However, this is ok:
  relation.select('distinct :id, :user_id').uniq.count

gem 'composite_primary_keys', '=8.1.6'
Rails 4.2.10

**Comment by cfis** [comment]
Sorry, I'm not supporting CPK 8.x anymore.  Happy to accept a pull request if you want to submit one.
