### ISSUE TITLE
Error introduced into change to subquery_for for composite keys

### ISSUE THREAD

**Issue by balen** [composite-primary-keys/composite_primary_keys#482]
Using Rails 4.2 with the 8.1.6. It appears that the code that adjusts subquery_for breaks for models that do not have a composite key (only some of my models are using the composite key mechanism).

A fix is to change the code to test if the key is an array (hence composite). Suggested change could be (which worked in my quick test):

```
        if key.name.kind_of?(Array)
          subselect.project *key.name.map{|x| arel_table[x]}
        else
          subselect.project Arel.sql(key.name)
        end
```

**Comment by balen** [comment]
I see that there was an update recently that should fix this (https://github.com/composite-primary-keys/composite_primary_keys/pull/469). Any idea of when there will be a release for Rails 4.2?

**Comment by cfis** [comment]
Done.
