### ISSUE TITLE
Wrong predicate composing for jsonb key values

### ISSUE THREAD

**Issue by vitalyp** [composite-primary-keys/composite_primary_keys#487]
When I use jsonb field as a part of composite key, it produces error here:
https://github.com/composite-primary-keys/composite_primary_keys/blob/v11.2.0/lib/composite_primary_keys/composite_predicates.rb#L35
`eq_predicates = keys.zip(values).map do |key, value|`

The value of jsonb field is array of hashes, for example: `[{"key1": "val1", "key2": "val2"}]`
The error appears on `model.reload`

**Comment by cfis** [comment]
Hmm, yeah, never imagined someone would use a jsonb field as a key. Does using a single jsonb primary key work in regular active record?

**Comment by cfis** [comment]
I'm going to consider using a jsob field as part of a primary key as unsupported since it doesn't seem worth to try and fix this (and not sure how to fix it either for that matter).
