### ISSUE TITLE
model where with primary key broken

### ISSUE THREAD

**Issue by johannesluedke** [composite-primary-keys/composite_primary_keys#488]
For a model whose primary_key is a composite key, the following query

```
model.where(model.primary_key => "1/1").first
```

fails due to producing incorrect SQL 

```
SELECT  model.* FROM model WHERE model."primary_key_1,primary_key_2” = $1 ORDER BY model.primary_key2 ASC, model.“primary_key_2” ASC LIMIT $2
```
Note the part `model."primary_key_1,primary_key_2”` 

This used to work in version 10.x and produce the query

```
SELECT  "model".* FROM "model" WHERE "model"."primary_key_1" = $1 AND "model"."primary_key_2" = $2 ORDER BY "model"."primary_key_1" ASC, "model"."primary_key_2" ASC LIMIT $3  [["primary_key_1", 10], ["primary_key_2", 11], ["LIMIT", 1]]
```

**Comment by cfis** [comment]
Yes that should work. Would need more information. What version of composite primary keys?  What's the definition of the model look like?
