### ISSUE TITLE
(v9) building subquery actually sends the query

### ISSUE THREAD

**Issue by konk303** [composite-primary-keys/composite_primary_keys#498]
Not sure if v9 is still supported, but in v9.0.10 (with Rails5.0.7.2)
I see building query with subquery actually sends the subquery before building collect query.

```ruby
Reading.where(user_id: User.where(name: 'Santiago')).to_sql

# does return the query desired.
=> "SELECT readings.* FROM readings WHERE readings.user_id IN (SELECT users.id FROM users WHERE name='Santiago')"

# But it does fire extra query, even with `to_sql`
SELECT users.* FROM users where name='Santiago'
```

https://github.com/composite-primary-keys/composite_primary_keys/blob/b1026b75130d309ce5d0f8c10f5eb67aebf6e66c/lib/composite_primary_keys/relation/predicate_builder.rb#L12

this line does `Array(value)`, which sends `to_a` to value, thus sql is fired.

It seems lots of changes are made on f3a5bc90d41ca9691373036036f4794e2d516a72
and I am not sure if it's fixed in newer versions, since I'm stuck in rails5.0 on my project.

**Comment by cfis** [comment]
Ah, good point.  So v9 really isn't supported anymore...happy to take a patch though. You might want to check what changed between v9 and v10 to see if it got fixed there and backpatch it.

**Comment by cfis** [comment]
Closing since haven't hard back.
