### ISSUE TITLE
v8.1.7 on RubyGems does not match version hosted on GitHub

### ISSUE THREAD

**Issue by jbodah** [composite-primary-keys/composite_primary_keys#500]
Hey folks,

I was upgrading one of our older apps and am debugging some unexpected behavior when converting Arel to SQL using the MySQL adapter. I started digging around and noticed that composite_primary_keys was opening `ActiveRecord::ConnectionAdapters::AbstractMysqlAdapter`. Curiously though the same version hosted on GH _does not_ open this class (there is no file `lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb`). The last revision for 8.1.7 on GH is dated for 2014 but the last RubyGems push is dated for 2019. Maybe the RubyGems copy is legit but I wanted to throw it back to you for a sanity check

We are modifying our code to pull directly from GH in the meantime

```
$ gem contents composite_primary_keys | grep 8.1.7 | grep abstract_mysql_adapter
.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/composite_primary_keys-8.1.7/lib/composite_primary_keys/connection_adapters/abstract_mysql_adapter.rb
```

**Comment by jbodah** [comment]
Looks like the tags are not corresponding to the gem version; closing for now

**Comment by cfis** [comment]
Oh, that's not good, they definitely should.  So the tag 8.1.7 is incorrect?

**Comment by jbodah** [comment]
I noticed a few issues:

* v8.1.7 is pushed to RubyGems (this seems correct)
* The git tag `v8.1.7` references version 6.0.7 (see https://github.com/composite-primary-keys/composite_primary_keys/blob/v8.1.7/lib/composite_primary_keys/version.rb)
* The branch `ar_4.2.x` references 8.1.6 (see https://github.com/composite-primary-keys/composite_primary_keys/blob/ar_4.2.x/lib/composite_primary_keys/version.rb)

This all wound up being unrelated to our issue; these are just clerical. I have a fix for that which I'll upstream once we test it a bit further

**Comment by cfis** [comment]
Ah - thanks. I'll see if I can clean up.
