### ISSUE TITLE
Critical bug: comma is not allowed as a value of attribute which is a part of composite key

### ISSUE THREAD

**Issue by timanovsky** [composite-primary-keys/composite_primary_keys#505]
No idea how this trivial case have not been caught before. Tested with rails 4.2 and gem 8.1.0 - 8.1.7, but according to source code other versions should behave the same.

**Table**
```
  Table "public.test_models"
 Column |  Type   | Modifiers 
--------+---------+-----------
 c1     | integer | not null
 c2     | text    | not null
Indexes:
    "test_models_pkey" PRIMARY KEY, btree (c1, c2)
```

**Model** 
```ruby
class TestModel < ApplicationRecord
  self.primary_keys = :c1, :c2
end
```

**Repro**
```
> m = TestModel.create!(c1: 2, c2: "bbb,cccc")
=> #<TestModel:0x000000001a662a78 c1: 2, c2: "bbb,cccc">
> m.reload
NoMethodError: undefined method `length' for 2:Fixnum
from /home/timanovsky/.rvm/gems/ruby-2.3.8/gems/composite_primary_keys-8.1.7/lib/composite_primary_keys/relation/finder_methods.rb:140:in `block in find_some'
```

This is because this code for some reason parses attribute values recursively and splits strings : https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/composite_arrays.rb#L11

So `[2, "bbb,cccc"]` becomes `[2, ["bbb", "cccc"]]`

**Comment by cfis** [comment]
Interesting, guess no one has run into that before. Wonder if its true on later versions too.  I commented on the patch...

**Comment by cfis** [comment]
These changes were merged in and also ported to master branch.

**Comment by sitnikovme** [comment]
@cfis any plans for making this critical fix available for version 11 of the gem for rails 5?

**Comment by sitnikovme** [comment]
@cfis could you please take a look and merge https://github.com/composite-primary-keys/composite_primary_keys/pull/510 ?

**Comment by cfis** [comment]
Yes - done.
