### ISSUE TITLE
Primary Key value creates error while updating/deleting record

### ISSUE THREAD

**Issue by fnu-wtag** [composite-primary-keys/composite_primary_keys#508]
I am using this gem to implement multi-tenancy using [activerecord-multi-tenant](https://github.com/citusdata/activerecord-multi-tenant) gem where all models that are directly related to tenant holds composite primary key.

https://github.com/composite-primary-keys/composite_primary_keys/blob/2dbd7a9bbebc7f584c6ec618c7666e1a9a2e4231/lib/composite_primary_keys/persistence.rb#L27-L29

While updating or deleting any record in my project, this particular section of code doesn't work (both in `_update_record` and `_delete_record` method), as it gets `"id"` as primary_key and tries to implement `each_with_index` on primary_key which gives the following error:
`Rails -- Exception: NoMethodError: undefined method 'each_with_index' for "id":String`

Following is a screenshot taken from rails console to show what I got from primary_key.

![Screen Shot 2020-03-01 at 10 49 37 AM](https://user-images.githubusercontent.com/39872561/75619911-43e7f900-5bac-11ea-8f8c-21b6edf4f95b.png)

To make it work, i added a monkey patch in my project where instead of `primary_key.each_with_index` I used `primary_keys.each_with_index` which solved the issue as `primary_keys` has the value `["id", "tenant_id"]` where `each_with_index` doesn't create any error.

I am using postgresql 10.4, CPK 11.2.0, activerecord 5.2.1 and ruby 2.6.0

**Comment by cfis** [comment]
Note the full code is:

`if self.composite? && constraints[primary_key]
  primary_key_values = constraints.delete(primary_key)
  primary_key.each_with_index do |key, i|
    constraints[key] = primary_key_values[i]
  end
end`

Is composite? returning true? And if yes, then primary key should be an array.

Can you reproduce using the test data included in CPK?

**Comment by fnu-wtag** [comment]
Hi @cfis can you please clarify which one is the test data in CPK? And yes, `self.composite` is returning true, but `primary_key` is not an array as it has only `id` in it.

**Comment by cfis** [comment]
Test data is here:

https://github.com/composite-primary-keys/composite_primary_keys/tree/master/test/fixtures

Hmm, can you paste in the class definitions (the CPK part) for the model that has composite? true but primary_key is not an array?

**Comment by cfis** [comment]
Haven't heard back, so closing. Reopen if you still need help.
