### ISSUE TITLE
After installing gem, still seeing "WARNING: Active Record does not support composite primary key."

### ISSUE THREAD

**Issue by mike-loopvoc** [composite-primary-keys/composite_primary_keys#516]
Is this expected?  Or must I do something else to avoid it.

**Comment by cfis** [comment]
Its expected. Suppose we could silence that warning. What version of Rails?

**Comment by mike-loopvoc** [comment]
6.0.2.2 Sent from Mail for Windows 10 From: Charlie SavageSent: Monday, April 20, 2020 2:00 AMTo: composite-primary-keys/composite_primary_keysCc: mike-loopvoc; AuthorSubject: Re: [composite-primary-keys/composite_primary_keys] After installing gem, still seeing "WARNING: Active Record does not support composite primary key." (#516) Its expected. Suppose we could silence that warning. What version of Rails?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by maurercw** [comment]
I'm seeing that pesky message as well!  Running rails 5.2.4.2 currently.

**Comment by cfis** [comment]
Happy to take a patch!
