### ISSUE TITLE
sync_with_transaction_state removed in active record 6.1

### ISSUE THREAD

**Issue by gravitystorm** [composite-primary-keys/composite_primary_keys#522]
This is just a heads-up, since activerecord 6.1 hasn't been released yet, but I found this problem while working on something else entirely. 

`sync_with_transaction_state` is called from multiple places in composite_primary_keys, so will need updating for compatibility when 6.1 is released.

https://github.com/rails/rails/pull/39121

**Comment by cfis** [comment]
Thanks.  Patches welcomed :)

**Comment by gravitystorm** [comment]
See #531 for a related pull request.
