### ISSUE TITLE
SQL-SERVER: fail on insert when trigger defined. since 12.0.3

### ISSUE THREAD

**Issue by net1957** [composite-primary-keys/composite_primary_keys#535]
I Have a sql*table defined as:
_create table sktable
(
    id         int identity
                constraint PK_sktable
                primary key,
    created_at datetime2
                constraint DF_sktable_created_at default getdate() not null,
    data       xml
)
go_

a trigger is defines, so in the table definition  I added to the model:
ActiveRecord::ConnectionAdapters::SQLServerAdapter.exclude_output_inserted_table_names["sktable"] = true

I add records witrh:
Sktable.new(data: xml).save

in 12.0.2 the sql generated statement is:

<
EXEC sp_executesql N'INSERT INTO [sktable] ([created_at], [data])
 OUTPUT INSERTED.[id] VALUES (@0, @1)', N'@0 datetime2(7), @1 nvarchar(max)',
 @0 = '12-13-2020 18:06:38.2880237', @1 = N'<entries><entry><f1>1</f1><f2>deux</f2><f3>3</f3><f4>quatre 4</f4></entry><entry><f1>2</f1><f2>trois 3</f2><f3>33</f3><f4>cinq</f4></entry></entries>'
 [["created_at", nil], ["data", nil]]
>

in 12.0.3 the sql generated statement is:

<
EXEC sp_executesql N'DECLARE @ssaIdInsertTable table (["[id]"] bigint);
 # CPK # INSERT INTO [sktable] ([created_at], [data])
 OUTPUT INSERTED.["[id]"] INTO @ssaIdInsertTable VALUES (@0, @1)
 INSERT INTO [sktable] ([created_at], [data])
 OUTPUT INSERTED.[id] INTO @ssaIdInsertTable VALUES (@0, @1)
 SELECT CAST([id] AS bigint) FROM @ssaIdInsertTable', N'@0 datetime2(7), @1 nvarchar(max)',
 @0 = '12-13-2020 18:02:11.8268169', @1 = N'<entries><entry><f1>1</f1><f2>deux</f2><f3>3</f3><f4>quatre 4</f4></entry><entry><f1>2</f1><f2>trois 3</f2><f3>33</f3><f4>cinq</f4></entry></entries>' 
 [["created_at", nil], ["data", nil]]
>

and this fail whit error: _TinyTds::Error: Incorrect syntax near 'id'._

composite_primary_keys is not needed for this table. But in another part of this application I use a legacy Oracle DB that need it.

Any idea?

**Comment by cfis** [comment]
Hmm, that generated sql looks fairly different. That is done by the activerecord sql server gem. Are you using different version of it? If not, which version are you using and have you recently changed it?

**Comment by net1957** [comment]
Hello,

activerecord-sqlserver-adapter is on version 6.0.0 
Nothing has changed. In the preparation of a future move to rails 6.1 (actually on 6.0.3.4) I try to be current on all the gems.
If I revert back to composite_primary_keys version 12.0.2, all is working as expected.

Perhaps related to commit af98960

**Comment by cfis** [comment]
Yeah I suspect you are right. Will take a look.

**Comment by cfis** [comment]
Ok, I took a look at this, and I don't know. This error does not show up in the test database. I agree that mass updates and deletes are broken for sql server (and were before). But this is an insert statement.

What is @ssaIdInsertTable? Sure your code hasn't changed?

**Comment by net1957** [comment]
we can see @ssaIdInsertTabl in https://github.com/composite-primary-keys/composite_primary_keys/commit/af9896014b8b1d7d01542ca6e17b56c0e171b1e8 in file lib/composite_primary_keys/connection_adapters/sqlserver/database_statements.rb

I tested some times, only changing the version of the gem between 12.0.2 and 12.0.3 and it happened each time in 12.0.3 and never in 12.0.2. No other changes on the code.

**Comment by cfis** [comment]
Ah - that's helpful. Ok, what happened is that I updated the sqlserver adapter code that CPK overrides. Note this code is only triggered if the table is added to the "exclude_output_inserted_table_name" has in the apater. I guess you must be doing that? The tests don't do that, thus don't see an issue.

**Comment by cfis** [comment]
Try 12.0.5 and see if it works.

**Comment by net1957** [comment]
It works! Thanks for this last 2020 commit!

**Comment by cfis** [comment]
Great - thanks for helping to track this down!
