### ISSUE TITLE
NoMethodError (private method `column_for' called for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x00007f91fca21990> Did you mean?  columns):

### ISSUE THREAD

**Issue by kenpang89** [composite-primary-keys/composite_primary_keys#536]
I'm getting this error when I try to insert new record.
ruby -v : 2.6.6
rails -v : 6.0.3.4
composite_primary_keys (12.0.3)
activerecord (~> 6.0.0)

**Comment by cfis** [comment]
Can you provide a traceback please.

**Comment by conathan** [comment]
I am also having the same issue,

Ruby 2.5.5p157, from Centos 8.3
rails 6.0.3.4
composite_primary_keys 12.0.3


irb(main):004:0> u.add_wblist('test5@test.com', 'W')
  AmavisMailaddr Load (30.7ms)  SELECT `mailaddr`.* FROM `mailaddr` WHERE `mailaddr`.`email` = x'746573743540746573742e636f6d' ORDER BY `mailaddr`.`id` ASC LIMIT 1
   (15.3ms)  BEGIN
  AmavisMailaddr Create (14.0ms)  INSERT INTO `mailaddr` (`email`) VALUES (x'746573743540746573742e636f6d')
   (53.5ms)  COMMIT
   (14.4ms)  BEGIN
  AmavisWblist Create (15.0ms)  INSERT INTO `wblist` (`rid`, `sid`, `wb`) VALUES (3, 10, 'W')
   (41.2ms)  ROLLBACK
Traceback (most recent call last):
        2: from (irb):4
        1: from app/models/amavis_user.rb:17:in `add_wblist'
NoMethodError (private method `column_for' called for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x00005589012812e0>)


not a very useful stack trace, but the only instance of column_for that I see is in composite_primary_keys-12.0.3/lib/composite_primary_keys/connection_adapters/mysql/database_statements.rb.
        def insert(arel, name = nil, pk = nil, id_value = nil, sequence_name = nil, binds = [])
          ..
              column = self.column_for(arel.ast.relation.name, key)
              column.auto_increment? ? last_inserted_id(value) : nil
          ..

Which commenting out those, does allow things to work for me.  (In my case, they are not autoincrementing values, which seem to be what it is checking for, obviously not the correct solution)
* Seems to be protected in Rails 5.0.x - https://apidock.com/rails/v5.0.0.1/ActiveRecord/ConnectionAdapters/AbstractAdapter/column_for
* but private in later versions


(This is mapped to amavis_wblist, as documented at https://docs.iredmail.org/amavisd.sql.db.html,  I use: self.primary_keys = :rid, :sid).

**Comment by cfis** [comment]
This is fixed by #532.
