### ISSUE TITLE
uninitialized constant CompositePrimaryKeys::ActiveRecord::Batches::BatchEnumerator

### ISSUE THREAD

**Issue by jasonkarns** [composite-primary-keys/composite_primary_keys#538]
The Batches module in CPK references a non-existent constant. `BatchEnumerator` is not defined in the CPK gem.

```
NameError:
       uninitialized constant CompositePrimaryKeys::ActiveRecord::Batches::BatchEnumerator
     # /usr/local/share/gem/gems/composite_primary_keys-12.0.3/lib/composite_primary_keys/relation/batches.rb:7:in `in_batches'
```

I've temporarily worked around this issue with: `CompositePrimaryKeys::ActiveRecord::Batches::BatchEnumerator = ActiveRecord::Batches::BatchEnumerator`

**Comment by cfis** [comment]
Thanks for the report. Its not so easy triggering that code - but I added a test and pushed a fix.

**Comment by jasonkarns** [comment]
Awesome, thanks @cfis !!
