### ISSUE TITLE
Does #find_each and #in_batches work?

### ISSUE THREAD

**Issue by codeodor** [composite-primary-keys/composite_primary_keys#546]
I just found a bug in my Rails 6.0 app where I use #find_each and it only pulls the first batch and operates on it. 

I made a note that I need to check this in the Rails 6.1 PR, but wanted to open a new ticket in case someone else wants to look into it for 6.0 before I get to it.

**Comment by codeodor** [comment]
Note I'm not *sure* it's due to CPK but this is the first place I'd look if I had a moment.

**Comment by cfis** [comment]
There are some test cases for finding in batches...can you reproduce in CPK test set?

**Comment by codeodor** [comment]
The test seem to work, even if I re-work to be more similar to my app.

The problem in my app is not necessarily `#find_each` though: it's that the first batch is returning 1000 rows, but only 998 records, because some of the rows contain the same record more than once. 

I think this would be similar to: 

```ruby
  def test_find_each_with_scope_and_association
    scoped_departments = Department.includes({:employees => [:comments, :groups]}, :comments, :head).references(:employees, :comments, :groups, :head)
    collected_depts = []
    scoped_departments.find_each(:batch_size => 3) do |department|
      collected_depts << department
    end

    assert_equal(Department.count, collected_depts.uniq.length)
    assert collected_depts.count > 3
  end
```

In particular, including and referencing the `:head` association would return a row for more than one dept head in the query, but CPK seems to be running a different query first. It is getting the distinct records based on the CPK and then getting the main query.

However, my app is not doing that. It's just running the query that pulls all the data.

I don't know what would make my app do that while CPK behaves differently. Still investigating.

**Comment by codeodor** [comment]
Line 31 in `batches.rb` reads like this:

`records = batch_relation.records`

In CPK tests, it runs two queries: one to get the IDs and one to get the records for those IDs.

In my app, however, it only runs one query, as if somehow it recognizes the need for it in CPK but not in mine.

**Comment by codeodor** [comment]
Ok, if I correct the data in my app for the relationships of "has one" to where it actually only has one in the DB, this issue goes away. But, I don't understand why CPK would not exhibit the same problem, given that relationship with `head` on `department` should be the same thing: it pulls more than one record if it was in a query like this. So what is causing CPK to load by ID first, and my app not to do that?

**Comment by cfis** [comment]
Rails will do two queries if you use :includes as part of the query. Could that be it?
