### ISSUE TITLE
delete doesn't return count of affected records

### ISSUE THREAD

**Issue by donncha** [composite-primary-keys/composite_primary_keys#547]
`ActiveRecord::Persistence.delete(id_or_array)` is supposed to return the count of records deleted.

With CPK, it returns the array of ids passed into it.

The relevant code block is...
```
          id_or_array.each do |id|
            # Is the passed in id actually a record?
            id = id.kind_of?(::ActiveRecord::Base) ? id.id : id
            delete_by(cpk_id_predicate(self.arel_table, self.primary_key, id))
          end
```
which is just going to return `id_or_array`.

**Comment by cfis** [comment]
Ah - thanks for pointing out.

**Comment by cfis** [comment]
Are you working on Rails 6.0 or 6.1?
