### ISSUE TITLE
Find does not work without specifying values for both keys

### ISSUE THREAD

**Issue by donncha** [composite-primary-keys/composite_primary_keys#548]
Given a model defined with `primary key (attr1, attr2)`, in Rails 5.x & CPK 11, the following works...
```
SomeModel.find(100)
```
and results in the SQL
```
...WHERE `some_models`.`attr1` = 100
```

In Rails 6 w/ CPK 12, it fails as follows:
```
irb> SomeModel.find(100)
TypeError (wrong argument type Integer (must respond to :each))
```

However, if you modify the param to be an array, then it still fails unless you specify a value for the second part of the PK.
```
irb> SomeModel.find([100])
ActiveRecord::RecordNotFound (Couldn't find SomeModel with 'attr1,attr2'=[100])
```
and results in the SQL
```
...WHERE `some_models`.`attr1` = 100 AND `some_models`.`attr2` IS NULL
```

Looking at the code, it seems the problem is here:
```
    def cpk_id_predicate(table, keys, values)
      eq_predicates = keys.zip(values).map do |key, value|
        table[key].eq(value)
      end
      cpk_and_predicate(eq_predicates)
    end
```
That will explicitly add "WHERE attr IS NULL" for any PK not supplied. Perhaps if you reversed the zip, this would not happen?

For example, `values.zip(keys)` would only add WHERE clauses for the PK components which have been supplied? Not sure if this would break other parts though 🤷‍♂️

**Comment by cfis** [comment]
You can always do find(:attr1 => 100).

I'm not sure if we should or shouldn't support incomplete keys in a query.

**Comment by cfis** [comment]
@donncha - Rereading your comment, your idea of zipping first on values then keys is an interesting one. I made the change and all tests pass, so seems like it works. Mind trying against the master branch and see if it fixes your issue?
