### ISSUE TITLE
NULL's being turned into empty strings in DB queries

### ISSUE THREAD

**Issue by tonyho1992** [composite-primary-keys/composite_primary_keys#549]
I'm noticing a difference in queries between having composite_primary_keys when there are NULL fields in a primary_key. Here's an example:

```
class TestingModel < ActiveRecord::Base

end
```

```
class TestModel < ActiveRecord::Base
  has_one :testing_model, primary_key: 'testing_model_permalink', foreign_key: 'permalink'
end
```

TestModel has one element that looks like this:

![image](https://user-images.githubusercontent.com/619547/110989436-bc88a600-8326-11eb-8a7e-c6e3e353d780.png)

When I run `TestModel.includes(:testing_model)`, I get the following SQL log
```
TestModel Load (36.8ms)  SELECT `test_models`.* FROM `test_models`
TestingModel Load (36.3ms)  SELECT `testing_models`.* FROM `testing_models` WHERE `testing_models`.`permalink` IN ('')
```

It seems like `composite_primary_keys` is changing the `NULL` to `''`, even when I'm not using a composite primary key. Is there a setting or some way I can control this? 

For reference, here is the SQL log without `composite_primary_keys`:
```
TestModel Load (30.3ms)  SELECT `test_models`.* FROM `test_models`
```

**Comment by codeodor** [comment]
Maybe there was a spot where we call `#to_s` when we shouldn't if it was `nil.`

What version of CPK are you running? Is it on Rails 6.1?

**Comment by tonyho1992** [comment]
We're on ruby 2.3.8 / rails 4.2.11

We're using a branched version of `ar_4.2.x`

**Comment by cfis** [comment]
Hey @tonyho1992,

Maybe its like this - https://github.com/composite-primary-keys/composite_primary_keys/issues/306?

Unfortunately, as you probably know such an old version of Rails and CPK is no longer supported. I'm not sure if this issue is fixed in more recent versions of cpk, but you might want to do a quick experiment and find out.
