### ISSUE TITLE
NoMethodError (undefined method `composite?' for <uuid>:String)

### ISSUE THREAD

**Issue by LyricL-Gitster** [composite-primary-keys/composite_primary_keys#551]
Currently running off of master (d815939).

I'm seeing an issue that is apparently related to queries on relations... possibly related to UUID's?

In this example, my **users** table has a **team_id** pointing to the **teams** table. Both are keyed by UUIDs.
```
1 => User.find_by team: team.id
1 => #<User id: "ee87136f-a71d-448f-86bb-9e975091078f", team_id: "1689d0af-07b5-4410-9f5f-ca6eeafe253e", ...>
2 => User.where(any_condition: value).find_by team: team.id
2 => NoMethodError (undefined method `composite?' for "1689d0af-07b5-4410-9f5f-ca6eeafe253e":String)
3 => User.where(any_condition: value).find_by team_id: team.id
3 => #<User id: "ee87136f-a71d-448f-86bb-9e975091078f", team_id: "1689d0af-07b5-4410-9f5f-ca6eeafe253e", ...>
```

I'm having trouble getting a full stacktrace, but judging by the method name it seems like an issue with this gem. It's pretty easily worked around by using the right value of `team_id: team.id` or `team: team`, but usually Rails is more forgiving and this should probably work.

Thanks for your time!

**Comment by stevehill1981** [comment]
@LyricL-Gitster I just ran into this today, and your suggested fix worked beautifully. Thanks so much.

**Comment by codeodor** [comment]
@LyricL-Gitster could you grab a full stack trace? Thanks!

**Comment by LyricL-Gitster** [comment]
Sorry, for some reason I wasn't getting a full trace before and I assumed it was just being swallowed, but now I get this:
```
irb(main):001:0> User.where team: '123'
/Users/lyric/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/composite_primary_keys-d81593910833/lib/composite_primary_keys/relation/predicate_builder/association_query_value.rb:30:in `ids': undefined method `composite?' for "123":String (NoMethodError)
```

**Comment by LyricL-Gitster** [comment]
Sorry, for some reason I wasn't getting a full trace before and I assumed it was just being swallowed, but now I get this:
```
irb(main):001:0> User.where team: '123'
/Users/lyric/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/bundler/gems/composite_primary_keys-d81593910833/lib/composite_primary_keys/relation/predicate_builder/association_query_value.rb:30:in `ids': undefined method `composite?' for "123":String (NoMethodError)
```

**Comment by LyricL-Gitster** [comment]
I still _should_ be getting at least the `where` call in that trace as well... not sure why rails console isn't showing it. Maybe a Ruby 3 thing?

**Comment by codeodor** [comment]
Thanks @LyricL-Gitster!
