### ISSUE TITLE
Rails 6.1, default_scope , ArgumentError (wrong number of arguments (given 2, expected 1))

### ISSUE THREAD

**Issue by ningzhang422** [composite-primary-keys/composite_primary_keys#553]
I profit master in my project with Rails 6.1.0 and composite_primary_keys 13.0.0
https://stackoverflow.com/questions/67019545/migration-rails-6-1-argumenterror-exception-wrong-number-of-arguments?noredirect=1#comment118465545_67019545

**Comment by codeodor** [comment]
Can you upgrade to Rails 6.1.3? 

They made a change between 6.1.0 and 6.1.3 that broke things and since we hadn't released yet, we are just going to target that minor release and above. 

Thanks!
