### ISSUE TITLE
Don't share seen object cache between different join nodes

### ISSUE THREAD

**Issue by mattlong** [composite-primary-keys/composite_primary_keys#559]
Hello, I stumbled across a bug in composite_primary_key where objects are not added to any but the first association/join to a given model. It's the exact issue that was addressed in https://github.com/rails/rails/commit/d9dcae34c35756e8520c8ede82fb4d6ebc166f0b. Looking at the CPK code, that fix was not ported over.

I observed this using rails 5.2.6 and CPK 11.3.1. I'm happy to submit a PR for those two line changes, but don't know if this could be an indicator that other changes weren't ported over.

**Comment by cfis** [comment]
Its certainly possible a change wasn't ported over.  Rails 5.2 is fairly old though at this point and not actively supported by CPK. But happy to take a patch.

**Comment by cfis** [comment]
Going to close this since haven't heard back.

**Comment by cfis** [comment]
Note I did look at the CPK override for this in newer versions of Rails and the change has been ported.
