### ISSUE TITLE
Primary key based on through assocciation

### ISSUE THREAD

**Issue by eni9889** [composite-primary-keys/composite_primary_keys#565]
I have the following models:

```
Shop
   id
   belongs_to :user

EmailStatus
   email
   status

Customer
   shop_id
   email
   has_one :email_status, foreign_key: [:email, :user_id], primary_key: [:email, :user_id]
```

I want to be able to call `Customer.all.first.email_status` but when I do the`user_id` is nil. How do I get the composite keys lib to use the `shop.user_id` column?

I appreciate any help you can give.

**Comment by cfis** [comment]
Its hard to tell from your example, you aren't showing the user_id field in the EmailStatus or Customer table. In addition, not sure what you mean by shop.user_id column since you never specify it anyplace.

**Comment by cfis** [comment]
Going to close this since haven't heard back.
