### ISSUE TITLE
arm64-darwin-21

### ISSUE THREAD

**Issue by styrken** [composite-primary-keys/composite_primary_keys#580]
Hi,

I am getting this error while running `bundle install`

> Could not find gem 'composite_primary_key arm64-darwin-21' in any of the gem sources listed in your Gemfile.

Is there anything that can be done to fix that? Thank you

**Comment by cfis** [comment]
Hmm, composite_primary_key is pure ruby gem so the platform is irrelevant.

It does depends on some native gems (like postgresql) but that isn't what your error message mentions. I'm guessing this is something unique to your environment so closing.
