### ISSUE TITLE
cpk fails when used with rspec stub_model in rails 6.0

### ISSUE THREAD

**Issue by toddwf** [composite-primary-keys/composite_primary_keys#581]
There seems to be a longstanding issue with using cpk with rspec-mocks.   I only have a partial solution to the problem.  I'll post code after the weekend but I wanted to ask whether anyone's had problems with rspec stub_model (rspec 3.11.0 rspec-mocks 3.11.1) and since it is involving rspec (specifcally rspec-mocks) how it should be handled.   It would ultimately be a patch to the rspec code.

Thank you!

**Comment by cfis** [comment]
I've only ever used minitest with CPK so not sure. Good luck and happy to take a patch if you develop one.

**Comment by cfis** [comment]
Going to close since there hasn't been any followup.

**Comment by toddwf** [comment]
This is still an issue.  I had to create a monkeypatch to get around it and that has broken my tests due to the namespacing of the patch.    I looked through tests in the repo and didn't see one that looked like an explicit test on this issue.  I started the process to submit but the test env overhead is significant and I was pulled in other directions.  If there's a pre-built VM LMK, otherwise I'll get back to it when I can.   But this is very much an issue for me.  What do you do if no one else reports/confirms?  Leave it closed unless I can get the test env up and submit a patch or?

**Comment by cfis** [comment]
Hi toddwf - happy to reopen. If you had a test case to reproduce that would be great.

**Comment by toddwf** [comment]
I'm going to close this.  My previous comment conflated it with another issue.  If I am able to revisit it, I'll reopen it and submit a test case.

**Comment by cfis** [comment]
Sounds good - thanks.
