### ISSUE TITLE
Duplicate order columns on composite keys when reversing

### ISSUE THREAD

**Issue by ioev** [composite-primary-keys/composite_primary_keys#594]
I just noticed that when doing a query like:
```Employee.last```

It seems that the composite primary keys are duplicated, n times where n is the number of composite keys.

I'm wondering if it's because of this nested loop, that probably isn't supposed to be nested?
https://github.com/composite-primary-keys/composite_primary_keys/blob/master/lib/composite_primary_keys/relation/query_methods.rb#L20

**Comment by cfis** [comment]
Good catch - thanks for the report!
