### ISSUE TITLE
Is it possible to add License?

### ISSUE THREAD

**Issue by sonyshchuk** [composite-primary-keys/composite_primary_keys#598]
Hello there,

First of all, thanks for the great gem and your hard work!

Can I ask you about the license and, if that is possible, add it to the repo? Is it MIT by the way?

Thanks,
Sergiy

**Comment by codeodor** [comment]
Gemspec file lists the license as MIT: 

https://github.com/composite-primary-keys/composite_primary_keys/blob/358ef9b28f61c4204bb40ed9e8c03ef750a964a7/composite_primary_keys.gemspec#L25

**Comment by cfis** [comment]
Going to close this since the question seems answered. Reopen if needed.

**Comment by codeodor** [comment]
@cfis might not be a bad idea for us to also add a license file, which is what many folks check. I had to think for a long while as to why I thought this was an MIT-licensed project without that file to back up my thought, and then I remembered the gemspec had it! :D

**Comment by cfis** [comment]
Sure - feel free to add a file for MIT
