### ISSUE TITLE
CPK and hash-partitioned table in PostgreSQL - building records via parent association doesn't work

### ISSUE THREAD

**Issue by glizda** [composite-primary-keys/composite_primary_keys#616]
## Issue reproduced in the Ruby script that you can find at the and of my message

The ruby script at the end of my message (based on [active_record bug report template](https://github.com/rails/rails/blob/main/guides/bug_report_templates/active_record.rb)) presents a simplified version of my setup together with test cases that show my issue.

## Issue description

I have two tables - `bookings` and `booking_time_segments`.

`booking_time_segments` is partitioned using hash strategy (partition key `booking_id`) and has composite primary key (`booking_id, id`).

Here are the AR models:
```ruby
class Booking < ActiveRecord::Base
  has_many :booking_time_segments, autosave: true
end

class BookingTimeSegment < ActiveRecord::Base
  self.primary_keys = :booking_id, :id
  belongs_to :booking
end
```

In that setup, I do:
```ruby
booking = Booking.new

bts_params = [
  { duration_in_seconds: 100, sorting_id: 0 },
  { duration_in_seconds: 200, sorting_id: 1 },
  { duration_in_seconds: 300, sorting_id: 2 }
]

booking.booking_time_segments.build(bts_params)
```

The line `booking.booking_time_segments.build(bts_params)` returns (as expected) the array of three `BookingTimeSegment` objects, suggesting that they are being properly built based on the params:
```ruby
[#<BookingTimeSegment id: nil, duration_in_seconds: 100, sorting_id: 0, booking_id: nil, created_at: nil, updated_at: nil>, #<BookingTimeSegment id: nil, duration_in_seconds: 200, sorting_id: 1, booking_id: nil, created_at: nil, updated_at: nil>, #<BookingTimeSegment id: nil, duration_in_seconds: 300, sorting_id: 2, booking_id: nil, created_at: nil, updated_at: nil>]
```

However, they don't really get built and/or assigned properly. If I then call `booking.booking_time_segments` (on not yet persisted `booking`), I get only one child record (the last one from the previous array):
```ruby
#<ActiveRecord::Associations::CollectionProxy [#<BookingTimeSegment id: nil, duration_in_seconds: 300, sorting_id: 2, booking_id: nil, created_at: nil, updated_at: nil>]>
```

Later saving the `booking` record only creates one associated `booking_time_segment` record. My expectation is that all three `booking_time_segments` records get properly built, assigned to the `booking` parent and persisted when `booking` is persited.

## Question

What am I doing wrong? Is more configuration needed on my ActiveRecord model definitions? Or is such case not supported by the gem?

## Bug report - Ruby script

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  ruby "2.7.7"

  gem "composite_primary_keys", '~> 13.0.0'
  gem "pg", "~> 1.5.3"
  gem "rails", "~> 6.1.7.4"
end

require "active_record/railtie"
require "minitest/autorun"

class TestApp < Rails::Application
  config.load_defaults Rails::VERSION::STRING.to_f
  config.eager_load = false
  config.logger = Logger.new($stdout)

  ActiveRecord::Base.establish_connection(
    adapter: "postgresql",
    database: "composite_pk_test",
    host: "localhost",
    username: "postgres"
  )
end

ActiveRecord::Schema.define do
  drop_table :bookings
  drop_table :booking_time_segments

  create_table :bookings, force: true do |t|
  end

  execute <<-SQL
    CREATE TABLE booking_time_segments (
      id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      duration_in_seconds integer NOT NULL,
      sorting_id integer NOT NULL ,
      booking_id bigint NOT NULL,
      created_at timestamp without time zone NOT NULL,
      updated_at timestamp without time zone NOT NULL,
      PRIMARY KEY (booking_id, id)
    ) PARTITION BY HASH (booking_id);

    CREATE INDEX IF NOT EXISTS index_booking_time_segments_on_booking_id
      ON booking_time_segments (booking_id);

    CREATE TABLE booking_time_segments_1 PARTITION OF booking_time_segments
      FOR VALUES WITH (MODULUS 2, REMAINDER 0);

    CREATE TABLE booking_time_segments_2 PARTITION OF booking_time_segments
      FOR VALUES WITH (MODULUS 2, REMAINDER 1);
  SQL
end

class Booking < ActiveRecord::Base
  has_many :booking_time_segments, autosave: true
end

class BookingTimeSegment < ActiveRecord::Base
  self.primary_keys = :booking_id, :id
  belongs_to :booking
end

class BugTest < ActiveSupport::TestCase
  def test_building_booking_with_one_segment # this test passes correctly
    booking = Booking.new

    bts_params = [
      { duration_in_seconds: 100, sorting_id: 0 }
    ]

    booking.booking_time_segments.build(bts_params)
    booking.save

    assert_equal 1, booking.booking_time_segments.count

    segment = booking.booking_time_segments.first
    assert segment.id
    assert_equal booking.id, segment.booking_id
    assert_equal 100, segment.duration_in_seconds
    assert_equal 0, segment.sorting_id
  end

  def test_building_booking_with_multiple_segments # this test fails
    booking = Booking.new

    bts_params = [
      { duration_in_seconds: 100, sorting_id: 0 },
      { duration_in_seconds: 200, sorting_id: 1 },
      { duration_in_seconds: 300, sorting_id: 2 }
    ]

    assert_equal 3, bts_params.count

    booking.booking_time_segments.build(bts_params)
    puts booking.booking_time_segments.inspect # already here you can see that only one record got built/assigned
    booking.save
    puts booking.booking_time_segments.inspect # only one record got persisted

    assert_equal 3, booking.booking_time_segments.count # fails, because the actual count is 1
  end
end
```

**Comment by CGA1123** [comment]
Hey, further simplifying down the cause of this behaviour leads to the implementaion of `#eql?` and `#hash` on `ActiveRecord::Core`.

e.g. (with the same setup as in the parent comment)

```ruby
class BugTest < ActiveSupport::TestCase
  def test_equality
    # Booking has a single column PK.
    booking = Booking.new

    assert_equal booking, booking
    assert_not_equal Booking.new, Booking.new
    
    # BookingTimeSegment has a composite PK.
    segment = BookingTimeSegment.new

    assert_equal segment, segment

    # This should pass.
    assert_not_equal BookingTimeSegment.new, BookingTimeSegment.new
  end
end
```

The current implementation of `#eql?` or `#==` and `#hash` for records using composite keys does not match the behaviour of records with non-composite keys in active record.

New records with `nil` primary keys should be considered different from each other!

This appears to have been the case prior to 51f9a4b4a3c3b44dc344bc0387b7ce6140b31702 🤔 

---

The reason for it manifesting in `#build` is due to the use of a `Set` to maintain the pool of new records added to an associating, in particular the call to `Set#include?` in [`ActiveRecord::Associations::CollectionAssociation#replace_on_target`](https://github.com/rails/rails/blob/ac87f58207cff18880593263be9d83456aa3a2ef/activerecord/lib/active_record/associations/collection_association.rb#L450)

**Comment by cfis** [comment]
Thanks for the work tracking this down - and that is an old commit!

So what does ActiveRecord when comparing different records that have nil a nil key (or keys in new versions of AR)?

What to create a PR? It should be based on `def ==(comparison_object)` as closely as possible.

**Comment by CGA1123** [comment]
In 6.1 the comparison checks `!id.nil?` as a special case [src](https://github.com/rails/rails/blob/v6.1.7.10/activerecord/lib/active_record/core.rb#L637-L643)


I suppose we could override so that we check `!id.all?(&:nil?)`?

i.e. we could add:

```ruby
def ==(comparison_object)
  super ||
    comparison_object.instance_of?(self.class) &&
    !id.all(&:nil?) &&
    comparison_object.id == id
end

def hash
  if !id.all?(&:nil?)
    self.class.hash ^ id.hash
  else
    super
  end
end
```

**Comment by cfis** [comment]
Don't you want all keys to not be nil. So this isn't correct is it?

`!id.all?(&:nil?)`

If all are nil, then return false. Alternatively, if any are not nil then return true. That means you could have a mix of nil and not nil. Isn't this what you want instead?

`if id.all? {|key| !key.nil?}`

**Comment by CGA1123** [comment]
Yes! Just checked on [rails 7.2](https://github.com/rails/rails/blob/33beb0a38db1c058123a8e3cc298cad918adfe32/activerecord/lib/active_record/attribute_methods/composite_primary_key.rb#L16-L22) and if any of the values are `nil` then they are treated as distinct.

So `id.all? { |key| !key.nil? }` is what we want 👍

**Comment by glizda** [comment]
@cfis, thanks for quick answer and @CGA1123, thank you for the help :)

I will happily create a PR with the proposed fix. The question is, @cfis, which branch should the PR point to? `ar_6.1.x` or `master`? How will we/you release a new version? Will it be `14.0.10` or `13.0.4` (because the fix is supposed be for AR 6.1)?

**Comment by glizda** [comment]
☝️ Here's the PR to `ar_6.1.x` branch.

**Comment by CGA1123** [comment]
Have cherrypicked #617 onto a PR for master in #618 -- tested locally and new tests fail w/o the overrides of `#eql?` + `#hash` on master.

**Comment by glizda** [comment]
@cfis, when you will be able to release 13.0.4? I'm looking forward to using it our project as soon as possible. :)

**Comment by cfis** [comment]
Tried this evening, but Ruby Gems was down for maintenance when I tried. Also, I want to get the sqlite tests working on master, I was expecting them to succeed but same issue as on ar_6.1 branch.

**Comment by cfis** [comment]
Updates pushed.
